## **Tabela de Indicadores RQUAL (ANATEL)**



| Contadores Estatísticos                  | Sigla  | Descrição do Indicador                                                                 | Serviços Relacionados                     |  
|------------------------------------------|--------|---------------------------------------------------------------------------------------|-------------------------------------------|  
| **App ESAQ + Apps “minha prestadora”**   | IND1   | Conexão de chamadas na rede de acesso                                                  | SMP                                       |  
|                                          | IND2   | Queda de chamadas                                                                      | SMP                                       |  
|                                          | IND3   | Conexão de dados medida na rede de acesso                                              | SMP                                       |  
|                                          | IND4   | Cumprimento de velocidade de download e upload                                         | SMP e SCM                                 |  
|                                          | IND5   | Latência bidirecional da conexão de dados                                              | SMP e SCM                                 |  
|                                          | IND6   | Variação de latência da conexão de dados                                               | SMP e SCM                                 |  
|                                          | IND7   | Perda de pacotes da conexão de dados                                                   | SMP e SCM                                 |  
| **Alarmes de rede**                      | INF4   | Velocidade de download e upload                                                        | SMP e SCM                                 |  
|                                          | INF5   | Experiência do uso de aplicativos em redes de dados                                    | SMP e SCM                                 |  
|                                          | IND8   | Disponibilidade                                                                        | SMP, SCM, STFC e SeAC                     |  
| **Central de atendimento**               | IND9   | Cumprimento de prazo                                                                   | SCM, STFC e SeAC                          |  
|                                          | INF1   | Tempo médio de instalação, reparo e mudança de endereço                                | SCM, STFC e SeAC                          |  
|                                          | INF2   | Tempo médio de espera para atendimento em centro de atendimento                        | SMP, SCM, STFC e SeAC                     |  
|                                          | INF3   | Tratamento de reclamações na Anatel                                                    | SMP, SCM, STFC e SeAC                     |  
| **Cobertura Mosaico**                    | IR     | Reclamações na Anatel                                                                  | SMP, SCM, STFC e SeAC                     |  
| **Status TUP (SGMU)**                    | INF6   | Cobertura dos serviços                                                                 | SMP                                       |  
| **Multicoletor (SM no modem)**           | INF7   | Disponibilidade de TUPs                                                               | STFC                                      |  
|                                          | INF8   | Velocidade de download e upload (% de entrega do plano)                                | SCM                                       |  

---

### **Legenda dos Serviços**  
- **SMP**: Serviço Móvel Pessoal  
- **SCM**: Serviço de Comunicação Multimídia  
- **STFC**: Serviço Telefônico Fixo Comutado  
- **SeAC**: Serviço de Acesso Condicionado  

### **Observações**  
- **IND**: Indicadores de qualidade obrigatórios.  
- **INF**: Dados informativos complementares.  
- **IR**: Indicador de Reclamações.

#### **Tabela do Dataset Completo**  
| **Campo**               | **Sigla da Anatel** | **Serviços para Agregar** | **Fonte**                     | **Tipo** | **Exemplo**       | **Explicação**                                                                 |
|--------------------------|---------------------|---------------------------|-------------------------------|----------|-------------------|-------------------------------------------------------------------------------|
| `municipio`             | N/A                 | N/A                       | IBGE                          | Texto    | "São Paulo"       |Nome do município (só para visualização).                                     |
| `ano`                   | N/A                 | N/A                       | ANATEL/IBGE                   | Número   | 2023              | Ano de referência dos dados.                                                  |
| `trimestre`             | N/A                 | N/A                       | ANATEL (RQUAL)                | Número   | 3                 | Trimestre (se usar dados trimestrais da ANATEL).                              |                         |
| `renda_per_capita`      | N/A                 | N/A                       | IBGE (PNAD Contínua)          | Número   | 1_500.00          | Renda média mensal por pessoa (em R$).                                        |
| `latencia_media`        | **IND5**            | SMP, SCM                  | ANATEL (RQUAL)                | Número   | 45.2              | Latência da internet em milissegundos (média do município).                  |
| `velocidade_download`   | **IND4**, **INF4**  | SMP, SCM                  | ANATEL (RQUAL)                | Número   | 50.5              | Velocidade de download em Mbps (média ou mediana).                            |
| `disponibilidade`       | **IND8**            | SMP, SCM, STFC, SeAC      | ANATEL (RQUAL)                | Número   | 98.7              | % do tempo em que a internet ficou ativa.                                     |
| `reclamacoes`           | **IR**              | SMP, SCM, STFC, SeAC      | ANATEL (SAC)                  | Número   | 120               | Número total de reclamações no município.                                     |
| `num_operadoras`        | N/A                 | N/A                       | ANATEL (Cadastro)             | Número   | 3                 | Quantidade de operadoras atuando no município.                                |
| `cobertura_4g`          | **INF6**            | SMP                       | ANATEL (Mapas de Cobertura)   | Número   | 85.0              | % do município com sinal 4G.                                                  |
| `reclamacoes_per_capita`| **IR**              | SMP, SCM, STFC, SeAC      | *Calculado*                   | Número   | 10.0              | Reclamações por 10 mil habitantes (`(reclamacoes / populacao) * 10000`).      |
| `satisfacao_internet`   | N/A                 | N/A                       | CGI.br (TIC Domicílios)       | Número   | 7.5               | Nota média de satisfação (0 a 10). *Dados por UF, pode estimar para município*. |
| `fonte_velocidade`      | N/A                 | N/A                       | *Metadado*                    | Texto    | "ANATEL_RQUAL_2023_Q3" | De onde veio o dado (para rastrear).                                         |

## Code

In [ ]:
# Dependencias
import pandas as pd
import os

# pip install pyarrow  # Biblioteca para ler/escrever Parquet

In [7]:
# Criação de DF a partir de CSV
df_rqual = pd.read_csv(
    'Tabela_CSV_Indicadores_RQUAL_consolidados20250516.csv', 
    sep=';',                  # Separador de colunas (geralmente ',' ou ';')
    decimal=',',              # Separador decimal (',' para formato brasileiro)
    encoding='utf-8'          # Codificação (pode ser 'latin-1' se houver erros)
)

In [8]:
# Número de linhas e colunas
linhas, colunas = df_rqual.shape
print(f"O DataFrame tem {linhas} linhas e {colunas} colunas.")

# Memória total utilizada pelo DataFrame (em MB)
memoria_total = df_rqual.memory_usage(deep=True).sum() / (1024 ** 2)  # Converte para MB
print(f"O DataFrame ocupa {memoria_total:.2f} MB na memória.")

# 3. Tamanho em disco (se salvo em CSV)

# Calcular tamanho do arquivo em MB
tamanho_arquivo_mb = os.path.getsize('Tabela_CSV_Indicadores_RQUAL_consolidados20250516.csv') / (1024 ** 2)  # Bytes para MB
print(f"Tamanho do arquivo CSV: {tamanho_arquivo_mb:.2f} MB")

O DataFrame tem 5962723 linhas e 20 colunas.
O DataFrame ocupa 5745.39 MB na memória.
Tamanho do arquivo CSV: 975.60 MB

In [9]:
# Imprimir primeiras linhas
df_rqual.head()

,Ano,Mês,Serviço,Tipo,Grupo,UF,Município,Código IBGE,Prestadora,Indicador,Descrição,Resultado,Unidade de Medida,Valor de Referência Superior,Valor de Referência Inferior,Erro Amostral,Limite Inferior,Limite Superior,Fonte,nome_mun_norm
0,2022,3,Banda Larga Fixa,Indicador IQS,Redes,AL,Maceió,2704302,ALGAR,IND5,Latência bidirecional da conexão de dados,0,%,0.9500000000000002,0.65,70.7,0,70.7083,RQUAL_8ind-A.xlsx,maceio
1,2022,3,Banda Larga Fixa,Indicador IQS,Redes,AP,Macapá,1600303,CLARO,IND5,Latência bidirecional da conexão de dados,100,%,0.9500000000000002,0.65,31.62,68.3783,100,RQUAL_8ind-A.xlsx,macapa
2,2022,3,Banda Larga Fixa,Indicador IQS,Redes,AL,Maceió,2704302,CLARO,IND5,Latência bidirecional da conexão de dados,78.7878,%,0.9500000000000002,0.65,10.65,68.1282,89.4474,RQUAL_8ind-A.xlsx,maceio
3,2022,3,Banda Larga Fixa,Indicador IQS,Redes,AM,Manaus,1302603,CLARO,IND5,Latência bidirecional da conexão de dados,68.7774,%,0.9500000000000002,0.65,3.63,65.1406,72.4142,RQUAL_8ind-A.xlsx,manaus
4,2022,3,Banda Larga Fixa,Indicador IQS,Redes,AC,Rio Branco,1200401,CLARO,IND5,Latência bidirecional da conexão de dados,76.1904,%,0.9500000000000002,0.65,15.42,60.7606,91.6202,RQUAL_8ind-A.xlsx,rio branco

In [10]:
# Verifique os nomes exatos das colunas
print(df_rqual.columns.tolist())

['Ano', 'Mês', 'Serviço', 'Tipo', 'Grupo', 'UF', 'Município', 'Código IBGE', 'Prestadora', 'Indicador', 'Descrição', 'Resultado', 'Unidade de Medida', 'Valor de Referência Superior', 'Valor de Referência Inferior', 'Erro Amostral', 'Limite Inferior', 'Limite Superior', 'Fonte', 'nome_mun_norm']

In [11]:
### Excluir colunas que não serão utilizadas

# Lista das colunas a serem removidas
colunas_remover = [
    'Erro Amostral',
    'Limite Inferior',
    'Limite Superior',
    'nome_mun_norm'
]

# Criar novo DataFrame sem as colunas especificadas
df_rqual1 = df_rqual.drop(columns=colunas_remover, errors='ignore')

# Imprimir primeiras linhas
df_rqual1.head()

,Ano,Mês,Serviço,Tipo,Grupo,UF,Município,Código IBGE,Prestadora,Indicador,Descrição,Resultado,Unidade de Medida,Valor de Referência Superior,Valor de Referência Inferior,Fonte
0,2022,3,Banda Larga Fixa,Indicador IQS,Redes,AL,Maceió,2704302,ALGAR,IND5,Latência bidirecional da conexão de dados,0,%,0.9500000000000002,0.65,RQUAL_8ind-A.xlsx
1,2022,3,Banda Larga Fixa,Indicador IQS,Redes,AP,Macapá,1600303,CLARO,IND5,Latência bidirecional da conexão de dados,100,%,0.9500000000000002,0.65,RQUAL_8ind-A.xlsx
2,2022,3,Banda Larga Fixa,Indicador IQS,Redes,AL,Maceió,2704302,CLARO,IND5,Latência bidirecional da conexão de dados,78.7878,%,0.9500000000000002,0.65,RQUAL_8ind-A.xlsx
3,2022,3,Banda Larga Fixa,Indicador IQS,Redes,AM,Manaus,1302603,CLARO,IND5,Latência bidirecional da conexão de dados,68.7774,%,0.9500000000000002,0.65,RQUAL_8ind-A.xlsx
4,2022,3,Banda Larga Fixa,Indicador IQS,Redes,AC,Rio Branco,1200401,CLARO,IND5,Latência bidirecional da conexão de dados,76.1904,%,0.9500000000000002,0.65,RQUAL_8ind-A.xlsx

In [20]:
# Número de linhas e colunas
linhas, colunas = df_rqual1.shape
print(f"O DataFrame tem {linhas} linhas e {colunas} colunas.")

# Memória total utilizada pelo DataFrame (em MB)
memoria_total = df_rqual1.memory_usage(deep=True).sum() / (1024 ** 2)  # Converte para MB
print(f"O DataFrame ocupa {memoria_total:.2f} MB na memória.")

O DataFrame tem 5962723 linhas e 16 colunas.
O DataFrame ocupa 3355.43 MB na memória.

In [21]:
# Conversão para o tipo category
df_rqual1['Serviço'] = df_rqual1['Serviço'].astype('category')
df_rqual1['UF'] = df_rqual1['UF'].astype('category')
df_rqual1['Prestadora'] = df_rqual1['Prestadora'].astype('category')
df_rqual1['Tipo'] = df_rqual1['Tipo'].astype('category')

In [22]:
# Número de linhas e colunas
linhas, colunas = df_rqual1.shape
print(f"O DataFrame tem {linhas} linhas e {colunas} colunas.")

# Memória total utilizada pelo DataFrame (em MB)
memoria_total = df_rqual1.memory_usage(deep=True).sum() / (1024 ** 2)  # Converte para MB
print(f"O DataFrame ocupa {memoria_total:.2f} MB na memória.")

O DataFrame tem 5962723 linhas e 16 colunas.
O DataFrame ocupa 3355.43 MB na memória.

In [26]:
# Salvar em Parquet com compressão
df_rqual1.to_parquet(
    'dados_rqual_otimizado20250516.parquet',
    compression='gzip',  # Compactação eficiente
    engine='pyarrow'
)

In [27]:
# Carregar o DataFrame
df_parquet = pd.read_parquet("dados_rqual_otimizado20250516.parquet")

In [28]:
# Número de linhas e colunas
linhas, colunas = df_parquet.shape
print(f"O DataFrame tem {linhas} linhas e {colunas} colunas.")

# Memória total utilizada pelo DataFrame (em MB)
memoria_total = df_parquet.memory_usage(deep=True).sum() / (1024 ** 2)  # Converte para MB
print(f"O DataFrame ocupa {memoria_total:.2f} MB na memória.")

# Primeiras linhas
df_parquet.head()

O DataFrame tem 5962723 linhas e 16 colunas.
O DataFrame ocupa 3215.96 MB na memória.

,Ano,Mês,Serviço,Tipo,Grupo,UF,Município,Código IBGE,Prestadora,Indicador,Descrição,Resultado,Unidade de Medida,Valor de Referência Superior,Valor de Referência Inferior,Fonte
0,2022,3,Banda Larga Fixa,Indicador IQS,Redes,AL,Maceió,2704302,ALGAR,IND5,Latência bidirecional da conexão de dados,0,%,0.9500000000000002,0.65,RQUAL_8ind-A.xlsx
1,2022,3,Banda Larga Fixa,Indicador IQS,Redes,AP,Macapá,1600303,CLARO,IND5,Latência bidirecional da conexão de dados,100,%,0.9500000000000002,0.65,RQUAL_8ind-A.xlsx
2,2022,3,Banda Larga Fixa,Indicador IQS,Redes,AL,Maceió,2704302,CLARO,IND5,Latência bidirecional da conexão de dados,78.7878,%,0.9500000000000002,0.65,RQUAL_8ind-A.xlsx
3,2022,3,Banda Larga Fixa,Indicador IQS,Redes,AM,Manaus,1302603,CLARO,IND5,Latência bidirecional da conexão de dados,68.7774,%,0.9500000000000002,0.65,RQUAL_8ind-A.xlsx
4,2022,3,Banda Larga Fixa,Indicador IQS,Redes,AC,Rio Branco,1200401,CLARO,IND5,Latência bidirecional da conexão de dados,76.1904,%,0.9500000000000002,0.65,RQUAL_8ind-A.xlsx