# Bibliotecas e dependencias

In [1]:
import re
from pathlib import Path
import numpy as np
import pandas as pd
import datetime
import os
import unicodedata
from typing import Iterable, Optional

# 1. Preparação de Dados Socioeconômicos  

**Artigo:**  
*Desigualdades Territoriais na Qualidade dos Serviços de Telecomunicações: Uma Análise Interpretável com Clusterização Espacial*

## Objetivo
O propósito central da preparação foi construir uma **base integrada, ampla e multidimensional** de dados socioeconômicos dos municípios brasileiros.  
Essa base consolida variáveis econômicas, demográficas, geográficas, administrativas e de desenvolvimento humano, permitindo análises exploratórias ricas e a aplicação de técnicas de clusterização.  

A ideia é oferecer um leque variado de variáveis, de modo que, em etapas posteriores, possamos selecionar aquelas que mais contribuem para **diferenciar perfis municipais** e formar **clusters homogêneos com maior potencial explicativo**.  

---

## 1. Fontes de Dados Utilizados  

### IBGE
- **PIB dos Municípios – 2010 a 2021**  
  https://www.ibge.gov.br/estatisticas/economicas/contas-nacionais/9088-produto-interno-bruto-dos-municipios.html  

- **Municípios + Latitude/Longitude**  
  https://www.ibge.gov.br/apps/pibmunic/  

- **Códigos, População, Área e Densidade – 2021**  
  https://biblioteca.ibge.gov.br/index.php/biblioteca-catalogo?id=2102057&view=detalhes  

- **Urbanização – 2022**  
  https://www.ibge.gov.br/estatisticas/downloads-estatisticas.html  

### PNUD / FJP / IPEA
- **Atlas Brasil – IDHM (2010)**  
  https://www.undp.org/pt/brazil/desenvolvimento-humano/atlas-do-desenvolvimento-humano-no-brasil  

---

## 2. Dados Intermediários
- PIB dos municipios do IBGE-2021.xlsx (**Filtragem**)  
- IDHM2010-atlasbr.xlsx (**Filtragem**)  
- IBGE_codmun-nommun-densid-2022.xlsx (**Filtragem**)  

---

## 3. Dado Final
- **base_integrada_ibge_municipios.csv**  

---

## Etapas da Preparação

1. **Coleta e integração de fontes oficiais**  
   - PIB dos Municípios (2021) – indicadores econômicos setoriais e agregados.  
   - População, Área e Densidade (2021) – estrutura territorial e demográfica.  
   - Urbanização (2022) – proporção da população urbana e rural.  
   - Atlas Brasil / PNUD – IDHM (2010).  
   - Cadastro georreferenciado – latitude/longitude, mesorregiões, microrregiões, hierarquias urbanas.  

   ➝ Todas as fontes foram harmonizadas pelo **código IBGE do município**, garantindo consistência.  

2. **Padronização das variáveis**  
   - Normalização de nomes e tipos de dados.  
   - Conversão de indicadores monetários para valores comparáveis.  
   - Remoção de duplicidades e de linhas agregadas (Brasil e UFs).  

3. **Criação da base integrada (56 variáveis)**  
   - **Identificação geográfica:** códigos e nomes de regiões, estados, municípios.  
   - **Localização administrativa:** latitude, longitude, capital, DDD, SIAFI, fuso horário.  
   - **Economia:** VAB setorial, PIB total, PIB per capita, impostos líquidos.  
   - **Demografia e território:** população, área, densidade demográfica.  
   - **Urbanização:** taxa de urbanização, população urbana e rural.  
   - **Desenvolvimento humano:** IDHM.  
   - **Estrutura produtiva:** principais atividades econômicas municipais.  

---

## Justificativa da Abordagem

- **Amplitude vs. Seletividade**  
  Construímos uma base ampla para permitir que métodos de seleção identifiquem as variáveis mais explicativas.  

- **Clusterização orientada a variáveis latentes**  
  A diversidade de variáveis abre espaço para métodos não supervisionados (K-means, DBSCAN, Hierárquica, SOM), avaliando dimensões mais relevantes na formação de grupos.  

- **Potencial para insights aplicados**  
  - Identificação de **perfis municipais** (agrícolas, industriais, urbanos, vulneráveis).  
  - **Comparação regional** para orientar políticas públicas.  
  - Base para **análises preditivas** e simulações de impacto.  

---

## Exemplos de Uso Posterior
1. **Pré-processamento estatístico** – padronização (z-score, min-max).  
2. **Redução de dimensionalidade** – PCA, t-SNE, UMAP.  
3. **Clusterização** – identificação de perfis socioeconômicos municipais.  
4. **Validação** – cruzamento dos clusters com indicadores externos (IDHM, qualidade de vida, resultados eleitorais).  

---

A preparação resultou em uma **infraestrutura de dados ampla e integrada**, que não só apoia a clusterização, mas também serve como base para **análises exploratórias, relatórios estratégicos e políticas públicas baseadas em evidências**.

# 2. Dicionários de Dados

## 2.1 PIB dos Municipios - base de dados 2010-2021.xlsx e PIB dos Municipios-IBGE-2021.xlsx

### Resumo
| Item   | Descrição |
|--------|-----------|
| **Aba** | 2021 (única presente no arquivo) |
| **Linhas** | 5.570 (cada linha representa um município brasileiro em 2021) |
| **Colunas principais** | 42, cobrindo desde georreferenciamento até detalhamento setorial e rankings de atividades |

---

### Colunas por Categoria

### 1. Identificação geográfica
| Campo | Descrição | Exemplo |
|-------|-----------|---------|
| Código da Grande Região | Código numérico da macrorregião | 1 |
| Nome da Grande Região | Nome da macrorregião | Norte |
| Código da Unidade da Federação | Código IBGE do estado | 11 |
| Sigla da Unidade da Federação | Sigla da UF | RO |
| Nome da Unidade da Federação | Nome do estado | Rondônia |
| Código do Município | Código IBGE do município | 1100015 |
| Nome do Município | Nome do município | Alta Floresta D'Oeste |
| Código/Nome da Mesorregião | Identificação geográfica intermediária | 1102 / Leste Rondoniense |
| Código/Nome da Microrregião | Subdivisão geográfica | 11006 / Cacoal |
| Região Metropolitana | Nome da RM (se aplicável) | nan |

### 2. Setores econômicos
| Campo | Descrição | Exemplo |
|-------|-----------|---------|
| VAB Agropecuária | Valor adicionado bruto da agropecuária (R$ mil) | 311468.683 |
| VAB Indústria | Valor adicionado bruto da indústria (R$ mil) | 27847.187 |
| VAB Serviços | Valor adicionado bruto dos serviços (exceto setor público) (R$ mil) | 172435.421 |
| VAB Administração Pública | Valor adicionado da administração pública, defesa, educação e saúde (R$ mil) | 173121.632 |

### 3. Agregados econômicos
| Campo | Descrição | Exemplo |
|-------|-----------|---------|
| VAB Total | Valor adicionado bruto total (R$ mil) | 684872.922 |
| Impostos Líquidos | Impostos líquidos sobre produtos (R$ mil) | 49596.402 |
| PIB | Produto Interno Bruto a preços correntes (R$ mil) | 734469.325 |
| PIB per capita | PIB per capita em reais correntes | 32619.88 |

### 4. Informações adicionais
| Campo | Descrição | Exemplo |
|-------|-----------|---------|
| Atividade com maior valor | Principal atividade econômica | Administração pública, defesa, educação e saúde |
| Atividade com segundo maior valor | Segunda atividade econômica | Pecuária |
| Atividade com terceiro maior valor | Terceira atividade econômica | Agricultura |

---

### Exemplo de Linha (Alta Floresta D’Oeste – RO):
1, Norte, 11, RO, Rondônia, 1100015, Alta Floresta D’Oeste, nan, 1102, Leste Rondoniense,
11006, Cacoal, …, 311468.683, 27847.187, 172435.421, 173121.632, 684872.922, 49596.402,
734469.325, 32619.88, Administração pública, Pecuária, Agricultura

## 2.2 municipios_latlong.xlsx

### Resumo
| Item   | Descrição |
|--------|-----------|
| **Aba** | municipios_latlong (única presente no arquivo) |
| **Linhas** | 5.570 (cada linha representa um município brasileiro) |
| **Colunas principais** | 9 campos: identificação, localização geográfica e características administrativas |

---

### Colunas por Categoria

### 1. Identificação
| Campo | Descrição | Exemplo |
|-------|-----------|---------|
| codigo_ibge | Código oficial do município no IBGE (7 dígitos) | 5200050 |
| nome | Nome do município | Abadia de Goiás |

### 2. Localização geográfica
| Campo | Descrição | Exemplo |
|-------|-----------|---------|
| latitude | Latitude aproximada do centro do município | -167573 |
| longitude | Longitude aproximada do centro do município | -494412.0 |

### 3. Características administrativas
| Campo | Descrição | Exemplo |
|-------|-----------|---------|
| capital | Indicador de capital (0 = não, 1 = sim) | 0 |
| codigo_uf | Código numérico da Unidade da Federação (UF) | 52 |
| siafi_id | Código no sistema SIAFI (Tesouro Nacional) | 1050 |
| ddd | Código DDD de telefonia | 62 |
| fuso_horario | Fuso horário do município | America/Sao_Paulo |

---

### Exemplo de Linha (Abadia de Goiás – GO)
5200050, Abadia de Goiás, -167573, -494412.0, 0, 52, 1050, 62, America/Sao_Paulo

## 2.3 IBGE_codmun-nommun-pop-area-densid-2021.xlsx

### Estrutura da Planilha – Códigos, População, Área e Densidade (IBGE, 2021)

### Resumo
| Item   | Descrição |
|--------|-----------|
| **Aba** | Tabela (principal) |
| **Linhas** | 5.575 (Brasil, Unidades da Federação e 5.570 municípios) |
| **Colunas principais** | 5 campos: código, município, população, área territorial e densidade demográfica |

---

### Colunas

| Campo | Descrição | Exemplo |
|-------|-----------|---------|
| codigo_ibge | Código oficial do município no IBGE (7 dígitos) | 1100015 |
| nome | Nome do município (com UF) | Alta Floresta D'Oeste (RO) |
| populacao_residente | População residente em 2021 (pessoas) | 21.494 |
| area_km2 | Área territorial (km²) | 7067.127 |
| densidade_hab_km2 | Densidade demográfica (habitantes/km²) | 3.04 |

---

### Exemplo de Linhas

- **Exemplos**:
	•	Brasil (nível agregado): 1, Brasil, 203080756, 8510417.771, 23.86
	•	Município (Alta Floresta D’Oeste – RO): 1100015, Alta Floresta D'Oeste (RO), 21494, 7067.127, 3.04

## 2.4 - IBGE-urbanizacao-2022.xlsx

### Estrutura da Planilha – Urbanização (IBGE, 2022)

### Resumo
| Item   | Descrição |
|--------|-----------|
| **Aba** | Tabela (principal) |
| **Linhas** | 5.575 (Brasil, Unidades da Federação e 5.570 municípios) |
| **Colunas principais** | 4 campos: município, população total, população urbana e população rural |

---

### Colunas

| Campo | Descrição | Exemplo |
|-------|-----------|---------|
| nome | Nome do município (com UF) ou unidade territorial (Brasil, estado) | Alta Floresta D'Oeste (RO) |
| populacao_total | População residente total em 2022 (pessoas) | 21.494 |
| populacao_urbana | População residente urbana em 2022 (pessoas) | 12.971 |
| populacao_rural | População residente rural em 2022 (pessoas) | 8.523 |

---

### Exemplo de Linhas

- **Brasil (nível agregado):** Brasil, 203080756, 177508417, 25572339
- **Município (Alta Floresta D’Oeste – RO):**  Alta Floresta D’Oeste (RO), 21494, 12971, 8523
- - **Município (Ariquemes – RO):**  Ariquemes (RO), 96833, 83952, 12881

## 2.5 - idhm-atlasbr.xlsx - 2010

### Estrutura da Planilha – Atlas Brasil / IDHM (2010 + Séries)

### Resumo
| Item   | Descrição |
|--------|-----------|
| **Aba** | Worksheet (principal) |
| **Linhas** | Brasil, Unidades da Federação e municípios |
| **Colunas principais** | 16 campos: identificação territorial, IDHM 2010, PIB per capita (2013–2016), população (2012–2021) |

---

### Colunas

| Campo | Descrição | Exemplo |
|-------|-----------|---------|
| territorialidade | Nome da unidade territorial (Brasil, UF ou município) | Acre |
| idhm_2010 | Índice de Desenvolvimento Humano Municipal (2010), varia de 0 a 1 | 0.663 |
| pib_per_capita_2013 | PIB per capita em 2013 (R$ correntes) | 12.37 |
| pib_per_capita_2014 | PIB per capita em 2014 (R$ correntes) | 13.41 |
| pib_per_capita_2015 | PIB per capita em 2015 (R$ correntes) | 12.24 |
| pib_per_capita_2016 | PIB per capita em 2016 (R$ correntes) | 11.18 |
| populacao_2012 | População residente em 2012 | 777.461 |
| populacao_2013 | População residente em 2013 | 790.155 |
| populacao_2014 | População residente em 2014 | 803.127 |
| populacao_2015 | População residente em 2015 | 816.230 |
| populacao_2016 | População residente em 2016 | 828.436 |
| populacao_2017 | População residente em 2017 | 840.491 |
| populacao_2018 | População residente em 2018 | 853.023 |
| populacao_2019 | População residente em 2019 | 865.422 |
| populacao_2020 | População residente em 2020 | 877.688 |
| populacao_2021 | População residente em 2021 | 889.829 |

---

### Exemplo de Linhas

- **Brasil (nível agregado):**  Brasil, 0.727, 22.20, 22.44, 21.17, 20.19, 197720534, 199402499, 201108347, 202858853, 204532351, 206172340, 207853293, 209496463, 211096453, 212650323
- **Estado (Acre):**  Acre, 0.663, 12.37, 13.41, 12.24, 11.18, 777461, 790155, 803127, 816230, 828436, 840491, 853023, 865422, 877688, 889829
- **Estado (Alagoas):**  Alagoas, 0.631, 9.45, 9.71, 10.02, 9.78, 3224172, 3240801, 3256780, 3272460, 3286849, 3300736, 3315564, 3330079, 3344244, 3358030

## 2.6  - base integrada

### Estrutura da Planilha – Base Integrada IBGE Municípios (CSV)

### Resumo
| Item   | Descrição |
|--------|-----------|
| **Arquivo** | base_integrada_ibge_municipios.csv |
| **Linhas** | 5.570 (cada linha representa um município brasileiro) |
| **Colunas** | 56 variáveis, integrando geografia, economia, demografia, urbanização e desenvolvimento humano |

---

### Colunas por Categoria

### 1. Identificação geográfica
| Campo | Descrição | Exemplo |
|-------|-----------|---------|
| cod_gd_reg | Código da Grande Região | 1 |
| gde_reg | Nome da Grande Região | Norte |
| cod_uf | Código da Unidade da Federação | 11 |
| sigla_uf | Sigla da Unidade da Federação | RO |
| nome_uf | Nome da Unidade da Federação | Rondônia |
| cod_mun | Código IBGE do município | 1100015 |
| nome_mun | Nome do município | Alta Floresta D'Oeste |
| regiao_metrop | Região metropolitana (se aplicável) | nan |
| cod_meso | Código da Mesorregião | 1102 |
| nome_meso | Nome da Mesorregião | Leste Rondoniense |
| cod_micro | Código da Microrregião | 11006 |
| nome_micro | Nome da Microrregião | Cacoal |
| cod_reg_imed | Código da Região Geográfica Imediata | 110005 |
| nome_reg_imed | Nome da Região Geográfica Imediata | Cacoal |
| mun_reg_imed | Município da Região Geográfica Imediata | do Entorno |
| cod_reg_intermed | Código da Região Geográfica Intermediária | 1102 |
| nome_reg_intermed | Nome da Região Geográfica Intermediária | Ji-Paraná |
| mun_reg_intermed | Município da Região Geográfica Intermediária | do Entorno |

---

### 2. Localização administrativa
| Campo | Descrição | Exemplo |
|-------|-----------|---------|
| cod_conc_urba | Código da Concentração Urbana | nan |
| nome_conc_urb | Nome da Concentração Urbana | nan |
| tipo_conc | Tipo da Concentração Urbana | nan |
| cod_arr | Código do Arranjo Populacional | nan |
| nome_arr | Nome do Arranjo Populacional | nan |
| hierarquia_urb | Hierarquia urbana | Centro Local |
| hier_cat | Hierarquia urbana (categorias principais) | Centro Local |
| cod_reg_rur | Código da Região Rural | 1101 |
| nome_reg_rur | Nome da Região Rural | Região Rural da Capital Regional de Porto Velho |
| tipo_reg_rural | Classificação do núcleo rural | Região Rural de Capital Regional |
| amaz_legal | Indicador de Amazônia Legal (Sim/Não) | Sim |
| semiarido | Indicador de Semiárido (Sim/Não) | Não |
| cid_reg_sao_paulo | Indicador de Cidade-Região de São Paulo (Sim/Não) | Não |

---

### 3. Economia
| Campo | Descrição | Exemplo |
|-------|-----------|---------|
| vr_agrop | VAB da Agropecuária (R$ mil) | 311468.683 |
| vr_ind | VAB da Indústria (R$ mil) | 27847.187 |
| vr_sv | VAB dos Serviços (exceto setor público) (R$ mil) | 172435.421 |
| vr_admin_pub | VAB da Administração pública (R$ mil) | 173121.632 |
| vr_ad_tot | Valor Adicionado Bruto Total (R$ mil) | 684872.922 |
| imp_liq | Impostos líquidos sobre produtos (R$ mil) | 49596.402 |
| pib_total | Produto Interno Bruto (R$ mil) | 734469.325 |
| pib_per_capita | PIB per capita (R$ correntes) | 32619.88 |
| ativ_mais_valor | Atividade com maior VAB | Administração pública |
| ativ_segundo_valor | Atividade com segundo maior VAB | Pecuária |
| ativ_terceiro_valor | Atividade com terceiro maior VAB | Agricultura |

---

### 4. Geolocalização
| Campo | Descrição | Exemplo |
|-------|-----------|---------|
| nome_mun_latlong | Nome do município (geocodificado) | Alta Floresta D'Oeste |
| latitude | Latitude do centro aproximado do município | -167573 |
| longitude | Longitude do centro aproximado do município | -494412.0 |
| codigo_uf | Código da UF (duplicado para consistência) | 11 |

---

### 5. População, território e densidade
| Campo | Descrição | Exemplo |
|-------|-----------|---------|
| nome_mun_dens | Nome do município (para cruzamento) | Alta Floresta D'Oeste |
| Pop | População residente (2021) | 21494 |
| Area | Área territorial (km²) | 7067.127 |
| DensDem | Densidade demográfica (hab/km²) | 3.04 |
| UF | Sigla da UF | RO |

---

### 6. Urbanização
| Campo | Descrição | Exemplo |
|-------|-----------|---------|
| TxUrb | Taxa de urbanização (proporção da população urbana) | 0.603471 |
| pop_urbana | População urbana | 12971 |
| pop_rural | População rural | 8523 |
| uf | Sigla da UF (duplicada) | RO |

---

### 7. Desenvolvimento humano
| Campo | Descrição | Exemplo |
|-------|-----------|---------|
| idhm_2010 | Índice de Desenvolvimento Humano Municipal (2010) | 0.641 |

---

### Exemplo de Linha (Alta Floresta D’Oeste – RO)
cod_gd_reg: 1
gde_reg: Norte
cod_uf: 11
sigla_uf: RO
nome_uf: Rondônia
cod_mun: 1100015
nome_mun: ALTA FLORESTA D'OESTE
latitude: -167573
longitude: -494412.0
capital: 0
Pop: 21494
Area: 7067.127
DensDem: 3.04
TxUrb: 0.603471
pop_urbana: 12971
pop_rural: 8523
idhm_2010: 0.641

### Revisão de Processamento dos Dados

## Objetivo
Revisar os datasets integrados, avaliando:
- **Campos-chave** (ex.: `codigo_ibge`/`cod_mun`) para garantir integridade na integração.
- **Unicidade e nulos** nas chaves.
- **Disponibilidade temporal** (anos de referência detectados nos campos).
- **Alinhamento entre bases** (interseções de municípios via código IBGE).

---

## Bases analisadas
- **PIB dos Municípios (2021)** — planilha `2021`
- **Municípios + Lat/Long** — planilha `municipios_latlong`
- **Códigos, População, Área e Densidade (2021)** — planilha `Tabela`
- **Urbanização (2022)** — planilha `Tabela`
- **Atlas Brasil / IDHM (2010 + séries)** — planilha `Worksheet`
- **Base Integrada (CSV)** — `base_integrada_ibge_municipios.csv`

---

## Relatórios gerados
- **relatorio_campos_temporalidade.csv**  
  Resumo por dataset (linhas, colunas, chave encontrada, duplicatas, nulos, anos detectados).
- **relatorio_chaves_alinhamento.csv**  
  Interseções de códigos IBGE entre bases.

---

## Pontos de atenção
- **Presença da chave**: deve existir em todas as bases.  
- **Duplicatas**: verificar se cada município aparece apenas uma vez.  
- **Nulos**: nenhum município deve ficar sem código.  
- **Temporalidade**: anos variam conforme a base (IDHM=2010, População=2012–2021, PIB=2021, Urbanização=2022).  
- **Alinhamento**: verificar cobertura total de 5.570 municípios.

In [2]:
# 1. Checar arquivos

# Definir aqui a pasta onde estão os arquivos
DATA_DIR = Path(".")

# Lista de arquivos esperados
arquivos_esperados = [
    "PIB dos Municipios - base de dados 2010-2021.xlsx",
    "municipios_latlong.xlsx",
    "IBGE_codmun-nommun-pop-area-densid-2021.xlsx",
    "IBGE-urbanizacao-2022.xlsx",
    "idhm-atlasbr.xlsx"
]

# Checar existência + metadados
for arq in arquivos_esperados:
    caminho = DATA_DIR / arq
    if caminho.exists():
        tamanho = os.path.getsize(caminho) / (1024 * 1024)  # em MB
        modificado = datetime.datetime.fromtimestamp(os.path.getmtime(caminho))
        print(f"✔️ {arq} existe")
        print(f"   - Tamanho: {tamanho:.2f} MB")
        print(f"   - Última modificação: {modificado}")
    else:
        print(f"❌ {arq} não encontrado")

✔️ PIB dos Municipios - base de dados 2010-2021.xlsx existe
   - Tamanho: 19.23 MB
   - Última modificação: 2025-10-03 12:59:57.744304
✔️ municipios_latlong.xlsx existe
   - Tamanho: 0.30 MB
   - Última modificação: 2025-05-01 09:36:28
✔️ IBGE_codmun-nommun-pop-area-densid-2021.xlsx existe
   - Tamanho: 0.30 MB
   - Última modificação: 2025-10-03 17:22:35.041092
✔️ IBGE-urbanizacao-2022.xlsx existe
   - Tamanho: 0.21 MB
   - Última modificação: 2025-10-03 17:24:04.818263
✔️ idhm-atlasbr.xlsx existe
   - Tamanho: 0.29 MB
   - Última modificação: 2025-10-03 18:16:00.067342

# 3. Revisão de Campos-Chave e Disponibilidade Temporal

In [3]:
# 2. Criar dataframes

# Lista de arquivos
arquivos_esperados = [
    "PIB dos Municipios - base de dados 2010-2021.xlsx",
    "municipios_latlong.xlsx",
    "IBGE_codmun-nommun-pop-area-densid-2021.xlsx",
    "IBGE-urbanizacao-2022.xlsx",
    "idhm-atlasbr.xlsx"
]

# Carregar DataFrames
df_pib = pd.read_excel(arquivos_esperados[0], sheet_name="2021")
df_latlong = pd.read_excel(arquivos_esperados[1], sheet_name="municipios_latlong")
df_popdens  = pd.read_excel(arquivos_esperados[2], sheet_name=0)
df_urban = pd.read_excel(arquivos_esperados[3], sheet_name=0)
df_idhm = pd.read_excel(arquivos_esperados[4], sheet_name="Worksheet")

# Mostrar formatos
print("📊 Formato das tabelas:")
print("PIB:", df_pib.shape)
print("LATLONG:", df_latlong.shape)
print("POP_DENS:", df_popdens.shape)
print("URBAN:", df_urban.shape)
print("IDHM:", df_idhm.shape)

📊 Formato das tabelas:
PIB: (5570, 42)
LATLONG: (5570, 9)
POP_DENS: (5570, 6)
URBAN: (5570, 4)
IDHM: (5565, 16)

In [4]:
# 3. Normalização de colunas nos 5 DataFrames principais

# Função de normalização
def normalize_columns(df: pd.DataFrame):
    """
    Retorna (df_norm, mapping_original_para_normalizado).
    - Converte para minúsculas
    - Troca espaços por _
    - Remove acentos e caracteres especiais
    - Mantém apenas letras, números e _
    """
    mapping = {}
    new_cols = []
    for c in df.columns:
        n = str(c).strip().lower().replace("\n", " ")
        n = (
            n.replace("ã","a").replace("á","a").replace("â","a").replace("à","a")
             .replace("é","e").replace("ê","e").replace("è","e")
             .replace("í","i").replace("ì","i")
             .replace("ó","o").replace("ô","o").replace("ò","o")
             .replace("ú","u").replace("ù","u")
             .replace("ç","c")
        )
        n = re.sub(r"\s+", "_", n)         # espaços -> _
        n = re.sub(r"[^\w_]", "", n)       # remove tudo que não é letra, número ou _
        mapping[c] = n
        new_cols.append(n)
    out = df.copy()
    out.columns = new_cols
    return out, mapping

# Dicionário com os DataFrames originais
dfs = {
    "PIB": df_pib,
    "LATLONG": df_latlong,
    "POP_DENS": df_popdens,
    "URBAN": df_urban,
    "IDHM": df_idhm,
}

# Aplicar normalização
dfs_norm = {}
mappings = {}

for name, df in dfs.items():
    df_norm, mapping = normalize_columns(df)
    dfs_norm[name] = df_norm
    mappings[name] = mapping
    
    # Mostrar resumo
    print(f"\n📂 Dataset: {name}")
    print("Número de colunas:", len(df.columns))
    print("Exemplo de mapping (origem -> normalizado):")
    for orig, norm in list(mapping.items())[:8]:  # mostra os 8 primeiros
        print(f"  {orig} --> {norm}")

📂 Dataset: PIB
Número de colunas: 42
Exemplo de mapping (origem -> normalizado):
  Código da Grande Região --> codigo_da_grande_regiao
  Nome da Grande Região --> nome_da_grande_regiao
  Código da Unidade da Federação --> codigo_da_unidade_da_federacao
  Sigla da Unidade da Federação --> sigla_da_unidade_da_federacao
  Nome da Unidade da Federação --> nome_da_unidade_da_federacao
  Código do Município --> codigo_do_municipio
  Nome do Município --> nome_do_municipio
  Região Metropolitana --> regiao_metropolitana

📂 Dataset: LATLONG
Número de colunas: 9
Exemplo de mapping (origem -> normalizado):
  codigo_ibge --> codigo_ibge
  nome --> nome
  latitude --> latitude
  longitude --> longitude
  capital --> capital
  codigo_uf --> codigo_uf
  siafi_id --> siafi_id
  ddd --> ddd

📂 Dataset: POP_DENS
Número de colunas: 6
Exemplo de mapping (origem -> normalizado):
  Nível --> nivel
  Cód. --> cod
  Brasil e Município --> brasil_e_municipio
  População residente (Pessoas) --> populacao_residente_pessoas
  Área da unidade territorial (Quilômetros quadrados) --> area_da_unidade_territorial_quilometros_quadrados
  Densidade demográfica (Habitante por quilômetro quadrado) --> densidade_demografica_habitante_por_quilometro_quadrado

📂 Dataset: URBAN
Número de colunas: 4
Exemplo de mapping (origem -> normalizado):
  Municipio --> municipio
  Total --> total
  Urbana --> urbana
  Rural --> rural

📂 Dataset: IDHM
Número de colunas: 16
Exemplo de mapping (origem -> normalizado):
  Territorialidades --> territorialidades
  IDHM 2010 --> idhm_2010
  Produto Interno Bruto per capita 2013 --> produto_interno_bruto_per_capita_2013
  Produto Interno Bruto per capita 2014 --> produto_interno_bruto_per_capita_2014
  Produto Interno Bruto per capita 2015 --> produto_interno_bruto_per_capita_2015
  Produto Interno Bruto per capita 2016 --> produto_interno_bruto_per_capita_2016
  População total 2012 --> populacao_total_2012
  População total 2013 --> populacao_total_2013

In [5]:
# 4. Perfilamento simples (nome dos campos)

import json

# Criar dicionário apenas com os nomes de colunas
perfis = {
    "PIB": list(df_pib.columns),
    "LATLONG": list(df_latlong.columns),
    "POP_DENS": list(df_popdens.columns),
    "URBAN": list(df_urban.columns),
    "IDHM": list(df_idhm.columns),
}

# Salvar em JSON
with open("perfil_campos.json", "w", encoding="utf-8") as f:
    json.dump(perfis, f, ensure_ascii=False, indent=2)

print("\n✅ Arquivo 'perfil_campos.json' gerado com sucesso!")

✅ Arquivo 'perfil_campos.json' gerado com sucesso!

In [6]:
# 5. Analise de campos para relacionamento dos arquivos

# Carregar o arquivo de perfil de campos
with open("perfil_campos.json", "r", encoding="utf-8") as f:
    perfil = json.load(f)

# Heurísticas de padrões de campos-chave
padroes = {
    "codigo_municipio": re.compile(r"(c[oó]d.*munic|codigo_ibge|cód\.)", re.IGNORECASE),
    "nome_municipio": re.compile(r"(nome.*munic|municipio|brasil e municipio|territorialidades)", re.IGNORECASE),
    "codigo_uf": re.compile(r"(c[oó]d.*uf|sigla_uf)", re.IGNORECASE)
}

# Identificar campos-chave potenciais
resultados = {}
for dataset, campos in perfil.items():
    resultados[dataset] = {}
    for chave, regex in padroes.items():
        matches = [c for c in campos if regex.search(c)]
        if matches:
            resultados[dataset][chave] = matches

# Mostrar de forma amigável
print("🔑 Campos-chave potenciais por dataset:\n")
for ds, chaves in resultados.items():
    print(f"=== {ds} ===")
    for tipo, campos in chaves.items():
        print(f"  {tipo}: {campos}")
    print()

🔑 Campos-chave potenciais por dataset:

=== PIB ===
  codigo_municipio: ['Código do Município']
  nome_municipio: ['Nome do Município']

=== LATLONG ===
  codigo_municipio: ['codigo_ibge']
  codigo_uf: ['codigo_uf']

=== POP_DENS ===
  codigo_municipio: ['Cód.']

=== URBAN ===
  nome_municipio: ['Municipio']

=== IDHM ===
  nome_municipio: ['Territorialidades']

**Abordagem a ser seguida:**

1.	Eleger uma tabela-ponte com nome + UF + codigo_ibge. A melhor é LATLONG (tem nome, UF e código).
2.	Normalizar os nomes (sem acentos, caixa baixa, etc.) em URBAN, IDHM e LATLONG.
3.	Dar match determinístico por (nome_normalizado, UF) quando houver UF.
4.	Se não houver UF, casar por nome_normalizado e marcar ambiguidades (nomes repetidos em UFs diferentes) para revisão.
5.	Depois disso, URBAN_mapeada e IDHM_mapeada ganham codigo_ibge e passam a juntar com PIB, POP_DENS e a própria LATLONG pelo código.

# 4. Checando integridade dos arquivos

In [7]:
# 1. Checando integridade dos arquivos

df_pib = pd.read_excel(arquivos_esperados[0], sheet_name="2021")

## 1.1. df_pib - contar qtde de valores únicos para o cod do municipio, e padronização dos nomes de campos

# Usando alias "Código do Município" e "Nome do Município"
COL_PIB_COD  = "Código do Município"
COL_PIB_NOME = "Nome do Município"

# Contar valores totais
total = len(df_pib)

# Contar valores únicos - cod mun
unicos = df_pib[COL_PIB_COD].nunique()
nulos = df_pib[COL_PIB_COD].isna().sum()

# Contagem de valores únicos - nome mun
unicos1 = df_pib[COL_PIB_NOME].nunique()
nulos1 = df_pib[COL_PIB_NOME].isna().sum()

# Print
print(f"\nTotal de linhas: {total}")
print(f"Valores únicos em {COL_PIB_COD}: {unicos}")
print(f"Valores únicos em {COL_PIB_NOME}: {unicos1}")

print(f"Duplicados potenciais cod mun: {total - unicos}")
print(f"Duplicados potenciais nome mun: {total - unicos1}")

print(f"Nulos cod mun: {nulos}")
print(f"Nulos nome mun: {nulos1}")

# Padronizar nomes das colunas
df_pib = df_pib.rename(columns={
    COL_PIB_COD: "cod_mun",
    COL_PIB_NOME: "nome_mun"
})

print("\nColunas após renomear:")
print(df_pib.columns.tolist())

Total de linhas: 5570
Valores únicos em Código do Município: 5570
Valores únicos em Nome do Município: 5297
Duplicados potenciais cod mun: 0
Duplicados potenciais nome mun: 273
Nulos cod mun: 0
Nulos nome mun: 0

Colunas após renomear:
['Código da Grande Região', 'Nome da Grande Região', 'Código da Unidade da Federação', 'Sigla da Unidade da Federação', 'Nome da Unidade da Federação', 'cod_mun', 'nome_mun', 'Região Metropolitana', 'Código da Mesorregião', 'Nome da Mesorregião', 'Código da Microrregião', 'Nome da Microrregião', 'Código da Região Geográfica Imediata', 'Nome da Região Geográfica Imediata', 'Município da Região Geográfica Imediata', 'Código da Região Geográfica Intermediária', 'Nome da Região Geográfica Intermediária', 'Município da Região Geográfica Intermediária', 'Código Concentração Urbana', 'Nome Concentração Urbana', 'Tipo Concentração Urbana', 'Código Arranjo Populacional', 'Nome Arranjo Populacional', 'Hierarquia Urbana', 'Hierarquia Urbana (principais categorias)', 'Código da Região Rural', 'Nome da Região Rural', 'Região rural (segundo classificação do núcleo)', 'Amazônia Legal', 'Semiárido', 'Cidade-Região de São Paulo', 'Valor adicionado bruto da Agropecuária, \na preços correntes\n(R$ 1.000)', 'Valor adicionado bruto da Indústria,\na preços correntes\n(R$ 1.000)', 'Valor adicionado bruto dos Serviços,\na preços correntes \n- exceto Administração, defesa, educação e saúde públicas e seguridade social\n(R$ 1.000)', 'Valor adicionado bruto da Administração, defesa, educação e saúde públicas e seguridade social, \na preços correntes\n(R$ 1.000)', 'Valor adicionado bruto total, \na preços correntes\n(R$ 1.000)', 'Impostos, líquidos de subsídios, sobre produtos, \na preços correntes\n(R$ 1.000)', 'Produto Interno Bruto, \na preços correntes\n(R$ 1.000)', 'Produto Interno Bruto per capita, \na preços correntes\n(R$ 1,00)', 'Atividade com maior valor adicionado bruto', 'Atividade com segundo maior valor adicionado bruto', 'Atividade com terceiro maior valor adicionado bruto']

**Observação:**
- Mesmos nomes aparecem em mais de um estado. Ao validar unicos considedrando uma chave uf+nome_mun, o numero de valores unicos é de 5570!

In [8]:
# 1.1 - Validação adicional - df_pib, nome_mun

# Colunas originais no df_pib
COL_PIB_UF   = "Código da Unidade da Federação"
COL_PIB_NOME = "nome_mun"

# Contagem total
total = len(df_pib)

# Criar chave composta
df_pib["chave_uf_nome"] = df_pib[COL_PIB_UF].astype(str) + "_" + df_pib[COL_PIB_NOME].astype(str)

# Contagem de valores únicos
unicos_comp = df_pib["chave_uf_nome"].nunique()
nulos_uf = df_pib[COL_PIB_UF].isna().sum()
nulos_nome = df_pib[COL_PIB_NOME].isna().sum()

# Print resumo
print(f"Total de linhas: {total}")
print(f"Valores únicos em chave_uf_nome: {unicos_comp}")
print(f"Duplicados potenciais chave composta: {total - unicos_comp}")

print(f"Nulos em Código da UF: {nulos_uf}")
print(f"Nulos em Nome do Município: {nulos_nome}")

Total de linhas: 5570
Valores únicos em chave_uf_nome: 5570
Duplicados potenciais chave composta: 0
Nulos em Código da UF: 0
Nulos em Nome do Município: 0

In [9]:
# df_pib.head(2)

In [ ]:
# 1.2 Checando integridade do df_latlong

df_latlong = pd.read_excel(arquivos_esperados[1], sheet_name='municipios_latlong')

# Colunas originais
COL_LAT_COD  = 'codigo_ibge'
COL_LAT_NOME = 'nome'
COL_LAT_UF   = 'codigo_uf'

total = len(df_latlong)
unicos_cod  = df_latlong[COL_LAT_COD].nunique()
nulos_cod   = df_latlong[COL_LAT_COD].isna().sum()
unicos_nome = df_latlong[COL_LAT_NOME].nunique()
nulos_nome  = df_latlong[COL_LAT_NOME].isna().sum()
df_latlong['chave_uf_nome'] = df_latlong[COL_LAT_UF].astype(str) + '_' + df_latlong[COL_LAT_NOME].astype(str)
unicos_comp = df_latlong['chave_uf_nome'].nunique()

print(f'Total de linhas: {total}')
print(f'Valores únicos em {COL_LAT_COD}: {unicos_cod}')
print(f'Duplicados potenciais cod mun: {total - unicos_cod}')
print(f'Nulos em cod mun: {nulos_cod}')
print(f'Valores únicos em {COL_LAT_NOME}: {unicos_nome}')
print(f'Duplicados potenciais nome mun: {total - unicos_nome}')
print(f'Nulos em nome mun: {nulos_nome}')
print(f'Valores únicos em chave_uf_nome: {unicos_comp}')
print(f'Duplicados potenciais chave composta: {total - unicos_comp}')

# Renomear colunas principais
df_latlong = df_latlong.rename(columns={
    COL_LAT_COD:  'cod_mun',
    COL_LAT_NOME: 'nome_mun',
    COL_LAT_UF:   'uf',
    'latitude':   'lat',
    'longitude':  'lon',
})

# CORREÇÃO: coordenadas armazenadas no arquivo fonte como inteiros x10.000 (sem ponto decimal)
# Exemplo: latitude=-167573 -> -16.7573 graus | longitude=-494412 -> -49.4412 graus
# Intervalos validos para o Brasil: lat em [-34, +6] | lon em [-74, -28]
print(f'\nCoordenadas brutas (antes da correcao):')
print(f'  lat: [{df_latlong["lat"].min():.0f}, {df_latlong["lat"].max():.0f}]')
print(f'  lon: [{df_latlong["lon"].min():.0f}, {df_latlong["lon"].max():.0f}]')

df_latlong['lat'] = df_latlong['lat'] / 10_000
df_latlong['lon'] = df_latlong['lon'] / 10_000

assert df_latlong['lat'].between(-35, 7).all(),  'Latitudes fora do intervalo esperado para o Brasil'
assert df_latlong['lon'].between(-75, -27).all(), 'Longitudes fora do intervalo esperado para o Brasil'

print(f'\nCoordenadas corrigidas (div 10.000):')
print(f'  lat: [{df_latlong["lat"].min():.4f}, {df_latlong["lat"].max():.4f}]  (esperado: [-34, +6])')
print(f'  lon: [{df_latlong["lon"].min():.4f}, {df_latlong["lon"].max():.4f}]  (esperado: [-74, -28])')
print('\nColunas apos renomear:')
print(df_latlong.columns.tolist())

In [11]:
# df_latlong.head(2)

In [12]:
# 1.3 - Checando integridade do df_popdens

df_popdens  = pd.read_excel(arquivos_esperados[2], sheet_name=0)

# Colunas originais no arquivo de população/densidade
COL_POP_COD  = "Cód."
COL_POP_NOME = "Brasil e Município"
COL_POP_UF   = "UF"  # verifique o nome exato, pode ser "UF", "Sigla_UF" ou similar

total = len(df_popdens)

# Contagem de valores únicos - código do município
unicos_cod = df_popdens[COL_POP_COD].nunique()
nulos_cod  = df_popdens[COL_POP_COD].isna().sum()

# Contagem de valores únicos - nome do município
unicos_nome = df_popdens[COL_POP_NOME].nunique()
nulos_nome  = df_popdens[COL_POP_NOME].isna().sum()

# Chave composta UF + nome do município
if COL_POP_UF in df_popdens.columns:
    df_popdens["chave_uf_nome"] = df_popdens[COL_POP_UF].astype(str) + "_" + df_popdens[COL_POP_NOME].astype(str)
    unicos_comp = df_popdens["chave_uf_nome"].nunique()
    print(f"\nValores únicos em chave_uf_nome: {unicos_comp}")
    print(f"Duplicados potenciais chave composta: {total - unicos_comp}")
else:
    print("\n⚠️ Nenhuma coluna de UF detectada — chave composta não pode ser avaliada diretamente.")

# Prints
print(f"Total de linhas: {total}")
print(f"Valores únicos em {COL_POP_COD}: {unicos_cod}")
print(f"Duplicados potenciais cod mun: {total - unicos_cod}")
print(f"Nulos em cod mun: {nulos_cod}")

print(f"\nValores únicos em {COL_POP_NOME}: {unicos_nome}")
print(f"Duplicados potenciais nome mun: {total - unicos_nome}")
print(f"Nulos em nome mun: {nulos_nome}")

# 2. Padronizar nomes das colunas principais
df_popdens = df_popdens.rename(columns={
    COL_POP_COD: "cod_mun",
    COL_POP_NOME: "nome_mun"
})
if COL_POP_UF in df_popdens.columns:
    df_popdens = df_popdens.rename(columns={COL_POP_UF: "uf"})

print("\nColunas após renomear:")
print(df_popdens.columns.tolist())

⚠️ Nenhuma coluna de UF detectada — chave composta não pode ser avaliada diretamente.
Total de linhas: 5570
Valores únicos em Cód.: 5570
Duplicados potenciais cod mun: 0
Nulos em cod mun: 0

Valores únicos em Brasil e Município: 5570
Duplicados potenciais nome mun: 0
Nulos em nome mun: 0

Colunas após renomear:
['Nível', 'cod_mun', 'nome_mun', 'População residente (Pessoas)', 'Área da unidade territorial (Quilômetros quadrados)', 'Densidade demográfica (Habitante por quilômetro quadrado)']

In [13]:
df_popdens.head(2)

,Nível,cod_mun,nome_mun,População residente (Pessoas),Área da unidade territorial (Quilômetros quadrados),Densidade demográfica (Habitante por quilômetro quadrado)
0,MU,1100015,Alta Floresta D'Oeste (RO),21494,7067.127,3.04
1,MU,1100023,Ariquemes (RO),96833,4426.571,21.88

In [14]:
# 1.3.1 - Separarando UF de nome_mun

# Copiar o df original para não sobrescrever
df_popdens_fixed = df_popdens.copy()

# Renomear a coluna certa (ajuste se o nome for diferente no seu arquivo)
if "nome_mun" not in df_popdens_fixed.columns:
    # supondo que a coluna esteja em "Unnamed: 1" ou similar
    # ajuste aqui se o nome for outro
    df_popdens_fixed = df_popdens_fixed.rename(columns={"Territorialidades": "nome_mun"})

# Extrair a UF (sigla entre parênteses)
df_popdens_fixed["uf"] = df_popdens_fixed["nome_mun"].str.extract(r"\((\w{2})\)")

# Limpar o nome do município (remover a UF entre parênteses)
df_popdens_fixed["nome_mun"] = (
    df_popdens_fixed["nome_mun"]
    .str.replace(r"\s*\(\w{2}\)$", "", regex=True)
    .str.strip()
)

# Checar resultado
print(df_popdens_fixed[["nome_mun","uf"]].head(10))
print("\nUFs detectadas:", df_popdens_fixed["uf"].unique()[:27])
print("Total de UFs:", df_popdens_fixed["uf"].nunique())

                nome_mun  uf
0  Alta Floresta D'Oeste  RO
1              Ariquemes  RO
2                 Cabixi  RO
3                 Cacoal  RO
4             Cerejeiras  RO
5      Colorado do Oeste  RO
6             Corumbiara  RO
7          Costa Marques  RO
8        Espigão D'Oeste  RO
9          Guajará-Mirim  RO

UFs detectadas: ['RO' 'AC' 'AM' 'RR' 'PA' 'AP' 'TO' 'MA' 'PI' 'CE' 'RN' 'PB' 'PE' 'AL'
 'SE' 'BA' 'MG' 'ES' 'RJ' 'SP' 'PR' 'SC' 'RS' 'MS' 'MT' 'GO' 'DF']
Total de UFs: 27

In [15]:
# 1.4 Checando integridade do df_urban

df_urban = pd.read_excel(arquivos_esperados[3], sheet_name=0)

# Coluna de município no arquivo urbanização
COL_URBAN_NOME = "Municipio"   # confirme o nome exato no seu df
COL_URBAN_UF   = "UF"          # se existir, pode ser "UF" ou "Sigla_UF"

total = len(df_urban)

# Contagem de valores únicos - nome do município
unicos_nome = df_urban[COL_URBAN_NOME].nunique()
nulos_nome  = df_urban[COL_URBAN_NOME].isna().sum()

# Chave composta UF + nome do município (se houver UF no dataset)
if COL_URBAN_UF in df_urban.columns:
    df_urban["chave_uf_nome"] = df_urban[COL_URBAN_UF].astype(str) + "_" + df_urban[COL_URBAN_NOME].astype(str)
    unicos_comp = df_urban["chave_uf_nome"].nunique()
    print(f"\nValores únicos em chave_uf_nome: {unicos_comp}")
    print(f"Duplicados potenciais chave composta: {total - unicos_comp}")
else:
    print("\n⚠️ Nenhuma coluna de UF detectada — chave composta não pode ser avaliada diretamente.")

# Prints
print(f"Total de linhas: {total}")
print(f"Valores únicos em {COL_URBAN_NOME}: {unicos_nome}")
print(f"Duplicados potenciais nome mun: {total - unicos_nome}")
print(f"Nulos em nome mun: {nulos_nome}")

# 2. Padronizar nomes das colunas
df_urban = df_urban.rename(columns={COL_URBAN_NOME: "nome_mun"})
if COL_URBAN_UF in df_urban.columns:
    df_urban = df_urban.rename(columns={COL_URBAN_UF: "uf"})

print("\nColunas após renomear:")
print(df_urban.columns.tolist())

⚠️ Nenhuma coluna de UF detectada — chave composta não pode ser avaliada diretamente.
Total de linhas: 5570
Valores únicos em Municipio: 5570
Duplicados potenciais nome mun: 0
Nulos em nome mun: 0

Colunas após renomear:
['nome_mun', 'Total', 'Urbana', 'Rural']

In [16]:
df_urban.head(2)

                     nome_mun  Total  Urbana  Rural
0  Alta Floresta D'Oeste (RO)  21494   12971   8523
1              Ariquemes (RO)  96833   83952  12881

In [17]:
# 1.4.1 -  Separando nome_mun de uf

# Faça uma cópia para não sobrescrever o original
df_urban_fixed = df_urban.copy()

# Garanta que a coluna de nome esteja com o alias esperado
# (ajuste se no seu arquivo a coluna tiver outro nome)
if "nome_mun" not in df_urban_fixed.columns:
    if "Municipio" in df_urban_fixed.columns:
        df_urban_fixed = df_urban_fixed.rename(columns={"Municipio": "nome_mun"})
    else:
        raise KeyError("Não encontrei a coluna de município em df_urban (ex.: 'Municipio' ou 'nome_mun').")

# 1) Extrair a UF no padrão "Nome (UF)" (duas letras)
df_urban_fixed["uf"] = df_urban_fixed["nome_mun"].str.extract(r"\((\w{2})\)")

# 2) Remover o sufixo " (UF)" do nome
df_urban_fixed["nome_mun"] = (
    df_urban_fixed["nome_mun"]
    .str.replace(r"\s*\(\w{2}\)$", "", regex=True)
    .str.strip()
)

# 3) Validação rápida
print("Amostra após separação de UF e nome:")
print(df_urban_fixed[["nome_mun", "uf"]].head(12).to_string(index=False))
print("\nUFs distintas detectadas:", df_urban_fixed["uf"].nunique())

Amostra após separação de UF e nome:
             nome_mun uf
Alta Floresta D'Oeste RO
            Ariquemes RO
               Cabixi RO
               Cacoal RO
           Cerejeiras RO
    Colorado do Oeste RO
           Corumbiara RO
        Costa Marques RO
      Espigão D'Oeste RO
        Guajará-Mirim RO
                 Jaru RO
            Ji-Paraná RO

UFs distintas detectadas: 27

In [18]:
df_urban_fixed.head(2)

                nome_mun  Total  Urbana  Rural  uf
0  Alta Floresta D'Oeste  21494   12971   8523  RO
1              Ariquemes  96833   83952  12881  RO

In [19]:
# 1.5 - Checando integridade do df_idhm

df_idhm = pd.read_excel(arquivos_esperados[4], sheet_name="Worksheet")

# Coluna de município (ou territorialidade) no IDHM
COL_IDHM_NOME = "Territorialidades"  # confirme no seu df
COL_IDHM_UF   = "UF"                 # só se existir

total = len(df_idhm)

# Contagem de valores únicos - territorialidade
unicos_nome = df_idhm[COL_IDHM_NOME].nunique()
nulos_nome  = df_idhm[COL_IDHM_NOME].isna().sum()

# Chave composta UF + nome (se houver coluna de UF)
if COL_IDHM_UF in df_idhm.columns:
    df_idhm["chave_uf_nome"] = df_idhm[COL_IDHM_UF].astype(str) + "_" + df_idhm[COL_IDHM_NOME].astype(str)
    unicos_comp = df_idhm["chave_uf_nome"].nunique()
    print(f"\nValores únicos em chave_uf_nome: {unicos_comp}")
    print(f"Duplicados potenciais chave composta: {total - unicos_comp}")
else:
    print("\n⚠️ Nenhuma coluna de UF detectada — chave composta não pode ser avaliada diretamente.")

# Prints
print(f"Total de linhas: {total}")
print(f"Valores únicos em {COL_IDHM_NOME}: {unicos_nome}")
print(f"Duplicados potenciais nome mun: {total - unicos_nome}")
print(f"Nulos em nome mun: {nulos_nome}")

# 2. Padronizar nomes das colunas principais
df_idhm = df_idhm.rename(columns={COL_IDHM_NOME: "nome_mun"})
if COL_IDHM_UF in df_idhm.columns:
    df_idhm = df_idhm.rename(columns={COL_IDHM_UF: "uf"})

print("\nColunas após renomear:")
print(df_idhm.columns.tolist())

⚠️ Nenhuma coluna de UF detectada — chave composta não pode ser avaliada diretamente.
Total de linhas: 5565
Valores únicos em Territorialidades: 5565
Duplicados potenciais nome mun: 0
Nulos em nome mun: 0

Colunas após renomear:
['nome_mun', 'IDHM 2010', 'Produto Interno Bruto per capita 2013', 'Produto Interno Bruto per capita 2014', 'Produto Interno Bruto per capita 2015', 'Produto Interno Bruto per capita 2016', 'População total 2012', 'População total 2013', 'População total 2014', 'População total 2015', 'População total 2016', 'População total 2017', 'População total 2018', 'População total 2019', 'População total 2020', 'População total 2021']

In [20]:
df_idhm.head(2)

,nome_mun,IDHM 2010,Produto Interno Bruto per capita 2013,Produto Interno Bruto per capita 2014,Produto Interno Bruto per capita 2015,Produto Interno Bruto per capita 2016,População total 2012,População total 2013,População total 2014,População total 2015,População total 2016,População total 2017,População total 2018,População total 2019,População total 2020,População total 2021
0,Abadia de Goiás (GO),0.708,17.62,18.86,15.70,13.72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Abadia dos Dourados (MG),0.689,16.66,21.55,16.93,16.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### **Observação 1:** Municípios criados no Brasil entre 2010 e 2021

Entre 2010 e 2021, o número de municípios brasileiros passou de **5.565** para **5.570**.  
Isso ocorreu devido à criação/instalação de **5 novos municípios**, todos reconhecidos oficialmente pelo IBGE a partir de 2013.

---

### Novos Municípios e seus Desmembramentos

| Município Novo (UF)        | Ano de Criação / Instalação | Município(s) de Origem (Desmembramento) |
|----------------------------|-----------------------------|-----------------------------------------|
| **Mojuí dos Campos (PA)**  | Criado em 2010 – instalado em 2013 | Desmembrado de **Santarém (PA)** |
| **Pinto Bandeira (RS)**    | Criado em 2012 – instalado em 2013 | Desmembrado de **Bento Gonçalves (RS)** |
| **Paraíso das Águas (MS)** | Criado em 2009 – instalado em 2013 | Desmembrado de **Água Clara (MS)**, **Camapuã (MS)** e **Costa Rica (MS)** |
| **Balneário Rincão (SC)**  | Criado em 2003 – instalado em 2013 | Desmembrado de **Içara (SC)** |
| **Pescaria Brava (SC)**    | Criado em 1995 – instalado em 2013 | Desmembrado de **Laguna (SC)** |

In [21]:
# 1.5.1 - Adicionando novos municipios, com valores interpolados a partir das origens

# ----------------------------
# 1) Definir novos municípios e origens, no padrão "Município (UF)"
# ----------------------------
novos_municipios = [
    {"nome_mun": "Mojuí dos Campos (PA)",  "origens": ["Santarém (PA)"]},
    {"nome_mun": "Pinto Bandeira (RS)",    "origens": ["Bento Gonçalves (RS)"]},
    {"nome_mun": "Paraíso das Águas (MS)", "origens": ["Água Clara (MS)", "Camapuã (MS)", "Costa Rica (MS)"]},
    {"nome_mun": "Balneário Rincão (SC)",  "origens": ["Içara (SC)"]},
    {"nome_mun": "Pescaria Brava (SC)",    "origens": ["Laguna (SC)"]},
]

# Coluna de pesos preferida
PESO_COL = "População total 2012"

# ----------------------------
# 2) Função de média ponderada por coluna numérica (ignorando NaN)
# ----------------------------
def media_ponderada_col(serie_vals: pd.Series, pesos: pd.Series):
    # Considera apenas posições onde há valor e (se existirem) pesos
    mask = serie_vals.notna()
    if not mask.any():
        return np.nan
    v = serie_vals[mask].astype(float)
    if pesos is None:
        return v.mean()
    w = pesos[mask].fillna(0)
    if (w > 0).sum() == 0:
        return v.mean()
    return np.average(v, weights=w)

# ----------------------------
# 3) Construir novas linhas
# ----------------------------
linhas_novas = []
nomes_existentes = set(df_idhm["nome_mun"].astype(str))

for mun in novos_municipios:
    # Validação de origens
    origens_df = df_idhm[df_idhm["nome_mun"].isin(mun["origens"])].copy()
    if origens_df.empty:
        print(f"⚠️ Não encontrei origens no IDHM para {mun['nome_mun']}: {mun['origens']}. Pulando.")
        continue

    # Pesos (se a coluna existir); senão, pesos iguais
    if PESO_COL in origens_df.columns:
        pesos = origens_df[PESO_COL]
    else:
        pesos = pd.Series(np.ones(len(origens_df)), index=origens_df.index)

    # Montar a nova linha
    nova_linha = {}
    for col in df_idhm.columns:
        if col == "nome_mun":
            nova_linha[col] = mun["nome_mun"]
        elif np.issubdtype(df_idhm[col].dtype, np.number):
            nova_linha[col] = media_ponderada_col(origens_df[col], pesos)
        else:
            # Campos não numéricos: copiar do primeiro (mantém consistência de metadados se houver)
            nova_linha[col] = origens_df[col].iloc[0]

    # Evitar duplicar se por acaso já existir
    if mun["nome_mun"] in nomes_existentes:
        print(f"ℹ️ '{mun['nome_mun']}' já existe no df_idhm. Não será adicionado novamente.")
    else:
        linhas_novas.append(nova_linha)

# ----------------------------
# 4) Concatenar e validar
# ----------------------------
df_novos = pd.DataFrame(linhas_novas)
df_idhm_expanded = pd.concat([df_idhm, df_novos], ignore_index=True)

print("Antes:", len(df_idhm))
print("Depois:", len(df_idhm_expanded))
print("Diferença:", len(df_idhm_expanded) - len(df_idhm))

# Preview de indicadores-chaves dos novos
cols_preview = ["nome_mun"] + [c for c in df_idhm.columns if ("IDHM" in c or "População total" in c)]
print("\nNovos adicionados (preview):")
print(df_novos[cols_preview].head(len(df_novos)).to_string(index=False))

Antes: 5565
Depois: 5570
Diferença: 5

Novos adicionados (preview):
              nome_mun  IDHM 2010  População total 2012  População total 2013  População total 2014  População total 2015  População total 2016  População total 2017  População total 2018  População total 2019  População total 2020  População total 2021
 Mojuí dos Campos (PA)      0.691                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN
   Pinto Bandeira (RS)      0.778                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN
Paraíso das Águas (MS)      0.693                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN
 Balneário Rincão (SC)      0.741                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN
   Pescaria Brava (SC)      0.752                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN                   NaN

In [22]:
total = len(df_idhm_expanded)
print(total)

5570

### **Observação 2:** nome_mun + (UF)

In [23]:
# 1.5.2 - Separar campo nome_mun

# Copiar para não sobrescrever
df_idhm_final = df_idhm_expanded.copy()

# Separar UF entre parênteses, criando coluna "uf"
df_idhm_final["uf"] = df_idhm_final["nome_mun"].str.extract(r"\((\w{2})\)")

# Remover a UF do nome do município -> vira só o nome limpo
df_idhm_final["nome_mun"] = df_idhm_final["nome_mun"].str.replace(r"\s*\(\w{2}\)$", "", regex=True).str.strip()

# Validar resultado
print(df_idhm_final[["nome_mun","uf"]].head(10))

# Conferir se todos ficaram com UF
print("\nUFs distintas detectadas:", df_idhm_final["uf"].nunique())
print("Exemplos de UFs:", df_idhm_final["uf"].unique()[:10])

              nome_mun  uf
0      Abadia de Goiás  GO
1  Abadia dos Dourados  MG
2            Abadiânia  GO
3               Abaeté  MG
4           Abaetetuba  PA
5              Abaiara  CE
6               Abaíra  BA
7                Abaré  BA
8               Abatiá  PR
9        Abdon Batista  SC

UFs distintas detectadas: 27
Exemplos de UFs: ['GO' 'MG' 'PA' 'CE' 'BA' 'PR' 'SC' 'PE' 'TO' 'MA']

# 5. Integrando os arquivos em um arquivo único

- df_pib
- df_popdens_fixed
- df_latlong
- df_urban_fixed
- df_idhm_expanded

## 5.1 Bloco 0 — Helpers (normalização de nomes + função de merge com prefixo)

In [24]:
# ======================================================
# BLOCO 0 — HELPERS GERAIS
# ======================================================
# O que faz:
#   • Define funções de apoio ao pipeline de integração.
#   • Mantém consistência entre merges, nomes e auditoria.
# Inclui:
#   - nome_norm_strong(): normalização robusta de nomes de municípios.
#   - merge_prefix_on_key(): merge com prefixo e checagem de cobertura.
#   - resumo_colunas(): exibe resumo compacto das colunas de um DataFrame.
# ======================================================

# ------------------------------------------------------
# Normalização forte de nomes de municípios
# ------------------------------------------------------
STOP = {"de", "da", "do", "das", "dos", "d"}

def nome_norm_strong(s: str) -> str:
    """Normaliza o nome do município para uso em chaves textuais."""
    if pd.isna(s):
        return ""
    s = str(s).lower().strip()
    s = unicodedata.normalize("NFKD", s).encode("ascii", "ignore").decode("utf-8")
    s = s.replace("’", "'").replace("´", "'").replace("`", "'")
    s = s.replace("-", " ").replace("/", " ")
    s = re.sub(r"(\b[dD])\s*'\s*", r"\1 ", s)
    s = re.sub(r"[^a-z0-9 ']+", " ", s)
    s = " ".join(s.split())
    tokens = [t for t in s.split() if t not in STOP]
    return "_".join(tokens)

# ------------------------------------------------------
# Merge com prefixo e validação
# ------------------------------------------------------
def merge_prefix_on_key(
    base: pd.DataFrame,
    df: pd.DataFrame,
    prefix: str,
    key: str = "cod_mun",
    include_cols: Optional[Iterable[str]] = None,
    validate: Optional[str] = "m:1",
) -> pd.DataFrame:
    """Faz merge LEFT de df em base pela chave `key`, prefixando as colunas."""
    if key not in base.columns or key not in df.columns:
        raise KeyError(f"Chave '{key}' ausente em um dos DataFrames.")
    
    # harmonizar tipos
    def _coerce_key(s: pd.Series) -> pd.Series:
        try:
            return pd.to_numeric(s, errors="coerce").astype("Int64")
        except Exception:
            return s.astype(str)
    
    base2, add = base.copy(), df.copy()
    base2[key], add[key] = _coerce_key(base[key]), _coerce_key(df[key])
    
    if base2[key].dtype != add[key].dtype:
        base2[key], add[key] = base[key].astype(str), df[key].astype(str)
    
    # restrição opcional
    if include_cols:
        add = add[[key] + [c for c in include_cols if c in add.columns]]
    
    add = add.drop_duplicates(subset=[key])
    cols_metrics = [c for c in add.columns if c != key]
    cols_metrics_pref = [c if c.startswith(prefix+"__") else prefix+"__"+c for c in cols_metrics]
    
    add_pref = pd.concat(
        [add[[key]].reset_index(drop=True),
         add[cols_metrics].set_axis(cols_metrics_pref, axis=1)], axis=1
    )
    
    out = base2.merge(add_pref, on=key, how="left", validate=validate)
    
    blk_cols = [c for c in out.columns if c.startswith(prefix+"__")]
    cov = out[blk_cols].notna().any(axis=1).sum() if blk_cols else 0
    print(f"[MERGE {prefix}] cols={out.shape[1]} | cobertura={cov}/{len(out)}")
    
    return out

# ------------------------------------------------------
# Resumo compacto de colunas (para inspeção rápida)
# ------------------------------------------------------
def resumo_colunas(df: pd.DataFrame, nome_df: str, max_cols: int = 10):
    """
    Mostra resumo do DataFrame:
      - nome
      - número de colunas
      - primeiros N nomes de colunas (ou todos, se menos de N)
    """
    total = len(df.columns)
    nomes = df.columns.tolist()
    preview = nomes[:max_cols]
    mais = f"... (+{total - max_cols})" if total > max_cols else ""
    print(f"{nome_df}: {total} colunas — ({', '.join(preview)}{mais})")

## 5.2 -  Bloco — Análise e registro das colunas do df_pib Criação do df base

In [25]:
# ======================================================
# BLOCO 1 — Análise do df_pib e criação da BASE
# Objetivo:
#   • Inspecionar rapidamente as colunas do df_pib (contagem e nomes).
#   • Criar o DataFrame 'base' a partir do df_pib, mantendo TODAS as colunas.
#   • Garantir a presença de chaves essenciais: cod_mun, nome_mun e uf.
#   • Remover duplicatas por cod_mun e reportar linhas/colunas finais.
# Observação:
#   • 'base' será o DataFrame canônico a ser enriquecido nos próximos merges.
# ======================================================

import pandas as pd

# 1) Inspeção rápida do df_pib
resumo_colunas(df_pib, "df_pib", max_cols=12)

# 2) Sanidade mínima de chaves esperadas
if "cod_mun" not in df_pib.columns:
    raise KeyError("df_pib precisa conter a coluna 'cod_mun'. Verifique a etapa de carregamento/normalização.")

if "nome_mun" not in df_pib.columns:
    # Tente detectar nome original e renomear (ajuste se necessário)
    cand = [c for c in df_pib.columns if "Nome do Município" in c or c.lower().strip() == "nome"]
    if cand:
        df_pib = df_pib.rename(columns={cand[0]: "nome_mun"})
    else:
        raise KeyError("df_pib não possui 'nome_mun' nem coluna equivalente detectável.")

# 3) Garantir coluna 'uf'
if "uf" not in df_pib.columns:
    # Tente usar a coluna "Sigla da Unidade da Federação"
    if "Sigla da Unidade da Federação" in df_pib.columns:
        df_pib = df_pib.rename(columns={"Sigla da Unidade da Federação": "uf"})
    else:
        # Derivar UF pelos 2 primeiros dígitos do cod_mun
        coduf_map = {
            11:"RO",12:"AC",13:"AM",14:"RR",15:"PA",16:"AP",17:"TO",
            21:"MA",22:"PI",23:"CE",24:"RN",25:"PB",26:"PE",27:"AL",28:"SE",29:"BA",
            31:"MG",32:"ES",33:"RJ",35:"SP",
            41:"PR",42:"SC",43:"RS",
            50:"MS",51:"MT",52:"GO",53:"DF"
        }
        df_pib = df_pib.copy()
        df_pib["uf"] = pd.to_numeric(df_pib["cod_mun"], errors="coerce").astype("Int64").astype(str).str[:2]
        df_pib["uf"] = pd.to_numeric(df_pib["uf"], errors="coerce").map(coduf_map)

# 4) Criar BASE com todas as colunas do df_pib
base = df_pib.copy()

# 5) Remover duplicatas por cod_mun (mantém a 1ª ocorrência)
linhas_antes = len(base)
base = base.drop_duplicates(subset=["cod_mun"]).reset_index(drop=True)
linhas_depois = len(base)

# 6) Relatórios de consistência
print("\n[BASE] Consistência inicial")
print(f" - Linhas (antes): {linhas_antes}")
print(f" - Linhas (depois de drop_duplicates por cod_mun): {linhas_depois}")
print(f" - Colunas: {len(base.columns)}")
print(" - Tem 'cod_mun'? ", "cod_mun" in base.columns)
print(" - Tem 'nome_mun'? ", "nome_mun" in base.columns)
print(" - Tem 'uf'? ", "uf" in base.columns)

# 7) (Opcional) Estatísticas rápidas da chave
n_unicos = base["cod_mun"].nunique()
n_nulos  = base["cod_mun"].isna().sum()
print(f"\n[BASE] cod_mun — únicos: {n_unicos} | nulos: {n_nulos}")

# 8) (Opcional) Guardar snapshot dos nomes de colunas para auditoria
colunas_iniciais_base = base.columns.tolist()
# with open("colunas_iniciais_base.json", "w", encoding="utf-8") as f:
#     import json; json.dump(colunas_iniciais_base, f, ensure_ascii=False, indent=2)

print("\n✅ BASE criada a partir do df_pib (todas as colunas mantidas). Pronta para os merges.")

df_pib: 43 colunas — (Código da Grande Região, Nome da Grande Região, Código da Unidade da Federação, Sigla da Unidade da Federação, Nome da Unidade da Federação, cod_mun, nome_mun, Região Metropolitana, Código da Mesorregião, Nome da Mesorregião, Código da Microrregião, Nome da Microrregião... (+31))

[BASE] Consistência inicial
 - Linhas (antes): 5570
 - Linhas (depois de drop_duplicates por cod_mun): 5570
 - Colunas: 43
 - Tem 'cod_mun'?  True
 - Tem 'nome_mun'?  True
 - Tem 'uf'?  True

[BASE] cod_mun — únicos: 5570 | nulos: 0

✅ BASE criada a partir do df_pib (todas as colunas mantidas). Pronta para os merges.

## 5.3 - Integtrando o df_popdens_fixed

In [26]:
# ======================================================
# BLOCO 2 — Merge POP (população/área/densidade) por cod_mun
# Objetivo:
#   • Integrar df_popdens_fixed à BASE por cod_mun.
#   • Manter rastreabilidade com prefixo POP__.
#   • Reportar cobertura e consistência pós-merge.
# ======================================================

# Resumo rápido do df_popdens_fixed
resumo_colunas(df_popdens_fixed, "df_popdens_fixed", max_cols=8)

# Sanidade mínima
assert "cod_mun" in df_popdens_fixed.columns, "df_popdens_fixed precisa ter 'cod_mun'."

# Guardar contagem de colunas antes do merge (para auditoria)
cols_antes = len(base.columns)

# Merge com prefixo
base = merge_prefix_on_key(base, df_popdens_fixed, prefix="POP", key="cod_mun")

# Consistência pós-merge
print("\n[CONSISTÊNCIA POP]")
print(f" - Linhas: {len(base)} (esperado: 5570)")
print(f" - Colunas antes: {cols_antes} | depois: {len(base.columns)} | adicionadas: {len(base.columns)-cols_antes}")

# (Opcional) conferir alguns campos do bloco POP
print("\nAmostra de colunas POP__:")
print([c for c in base.columns if c.startswith('POP__')][:8])

df_popdens_fixed: 7 colunas — (Nível, cod_mun, nome_mun, População residente (Pessoas), Área da unidade territorial (Quilômetros quadrados), Densidade demográfica (Habitante por quilômetro quadrado), uf)
[MERGE POP] cols=49 | cobertura=5570/5570

[CONSISTÊNCIA POP]
 - Linhas: 5570 (esperado: 5570)
 - Colunas antes: 43 | depois: 49 | adicionadas: 6

Amostra de colunas POP__:
['POP__Nível', 'POP__nome_mun', 'POP__População residente (Pessoas)', 'POP__Área da unidade territorial (Quilômetros quadrados)', 'POP__Densidade demográfica (Habitante por quilômetro quadrado)', 'POP__uf']

## 5.4 - Integrando o df_latlong

In [27]:
# ======================================================
# BLOCO 2 — Merge LATLONG (coordenadas geográficas)
# Objetivo:
#   • Integrar df_latlong via cod_mun.
#   • Acrescentar latitude e longitude aos dados-base.
#   • Validar consistência e cobertura.
# ======================================================

# Resumo rápido do df_latlong
resumo_colunas(df_latlong, "df_latlong", max_cols=6)

# Sanidade mínima
for col in ("cod_mun", "lat", "lon"):
    assert col in df_latlong.columns, f"df_latlong precisa ter '{col}'."

# Guardar colunas antes (para auditoria)
cols_antes = len(base.columns)

# Merge por cod_mun
base = merge_prefix_on_key(base, df_latlong, "LAT", key="cod_mun")

# Consistência e cobertura
cov_lat = base.filter(like="LAT__").notna().any(axis=1).sum()
print(f"\n[CONSISTÊNCIA LATLONG]")
print(f" - Linhas: {len(base)} (esperado: 5570)")
print(f" - Colunas antes: {cols_antes} | depois: {len(base.columns)} | adicionadas: {len(base.columns) - cols_antes}")
print(f" - Cobertura LAT: {cov_lat} / {len(base)}")

print("\nAmostra de colunas LAT__:")
print([c for c in base.columns if c.startswith('LAT__')][:10])

df_latlong: 10 colunas — (cod_mun, nome_mun, lat, lon, capital, uf... (+4))
[MERGE LAT] cols=58 | cobertura=5570/5570

[CONSISTÊNCIA LATLONG]
 - Linhas: 5570 (esperado: 5570)
 - Colunas antes: 49 | depois: 58 | adicionadas: 9
 - Cobertura LAT: 5570 / 5570

Amostra de colunas LAT__:
['LAT__nome_mun', 'LAT__lat', 'LAT__lon', 'LAT__capital', 'LAT__uf', 'LAT__siafi_id', 'LAT__ddd', 'LAT__fuso_horario', 'LAT__chave_uf_nome']

## 5.5 - Integrando o df_urban_fixed

In [28]:
# ======================================================
# BLOCO 4 — Merge URBAN (uf + nome normalizado) + PATCH documentado
# Objetivo:
#   • Integrar df_urban_fixed usando chave textual robusta (uf + nome_norm_strong).
#   • Evitar duplicidade (_x/_y) limpando URB__* antes do merge.
#   • Diagnosticar faltantes e aplicar patch pontual conhecido.
# Pré-requisitos:
#   • base criada (Blocos 1–3) com 'uf' e 'nome_mun'
#   • df_urban_fixed contém 'uf' e 'nome_mun'
#   • função nome_norm_strong disponível (Bloco 0)
# ======================================================

# 0) Limpeza preventiva: remover colunas URB__ antigas
base = base.drop(columns=[c for c in base.columns if c.startswith("URB__")], errors="ignore")

# 1) Sanidade + resumo
resumo_colunas(df_urban_fixed, "df_urban_fixed", max_cols=8)
for col in ("uf", "nome_mun"):
    assert col in df_urban_fixed.columns, f"df_urban_fixed precisa ter '{col}'."

cols_antes = len(base.columns)

# 2) Criar chave normalizada nos dois lados
b = base.copy()
b["_key_norm"] = b["uf"].astype(str) + "_" + b["nome_mun"].apply(nome_norm_strong)

u = df_urban_fixed.drop_duplicates(subset=["uf","nome_mun"]).copy()
u["_key_norm"] = u["uf"].astype(str) + "_" + u["nome_mun"].apply(nome_norm_strong)

# 3) Prefixar apenas métricas/atributos do URBAN (preservar chave)
cols_metrics_urb = [c for c in u.columns if c not in ["_key_norm","uf","nome_mun"]]
urb_pref = pd.concat([u[["_key_norm"]], u[cols_metrics_urb].add_prefix("URB__")], axis=1)

# 4) Merge por chave normalizada
base = b.merge(urb_pref, on="_key_norm", how="left").drop(columns="_key_norm")

# 5) Consistência e cobertura
cov_urb = base.filter(like="URB__").notna().any(axis=1).sum()
print(f"[MERGE URBAN] cols={len(base.columns)} | cobertura={cov_urb}/{len(base)}")
print("\n[CONSISTÊNCIA URBAN]")
print(f" - Linhas: {len(base)} (esperado: 5570)")
print(f" - Colunas antes: {cols_antes} | depois: {len(base.columns)} | adicionadas: {len(base.columns) - cols_antes}")

# 6) Diagnóstico de faltantes
faltantes_mask = ~base.filter(like="URB__").notna().any(axis=1)
faltantes = base.loc[faltantes_mask, ["cod_mun","uf","nome_mun"]].copy()
print(f"\n[URBAN] Faltantes: {len(faltantes)}")
if len(faltantes) > 0:
    print(faltantes.head(12).to_string(index=False))

# 7) PATCH pontual documentado (aplicado somente se necessário)
#    Caso conhecido: "Graccho Cardoso" (URBAN) -> "Gracho Cardoso" (BASE), UF = SE
if len(faltantes) > 0:
    # checar se o caso "Gracho Cardoso (SE)" está entre os faltantes
    precisa_patch_gc = ((faltantes["uf"] == "SE") & (faltantes["nome_mun"].str.strip().str.lower() == "gracho cardoso")).any()
    if precisa_patch_gc:
        # aplicar correção no df_urban_fixed
        mask_gc = (
            df_urban_fixed["uf"].eq("SE") &
            df_urban_fixed["nome_mun"].str.replace(r"\s+"," ", regex=True).str.strip().str.lower().eq("graccho cardoso")
        )
        n_corr = mask_gc.sum()
        if n_corr > 0:
            df_urban_fixed.loc[mask_gc, "nome_mun"] = "Gracho Cardoso"
            print(f"\n[PATCH URBAN] Corrigido nome em df_urban_fixed: 'Graccho Cardoso' → 'Gracho Cardoso' (SE). Linhas alteradas: {n_corr}")

            # --- refazer APENAS o merge URBAN ---
            base = base.drop(columns=[c for c in base.columns if c.startswith("URB__")], errors="ignore")

            b = base.copy()
            b["_key_norm"] = b["uf"].astype(str) + "_" + b["nome_mun"].apply(nome_norm_strong)

            u = df_urban_fixed.drop_duplicates(subset=["uf","nome_mun"]).copy()
            u["_key_norm"] = u["uf"].astype(str) + "_" + u["nome_mun"].apply(nome_norm_strong)

            cols_metrics_urb = [c for c in u.columns if c not in ["_key_norm","uf","nome_mun"]]
            urb_pref = pd.concat([u[["_key_norm"]], u[cols_metrics_urb].add_prefix("URB__")], axis=1)

            base = b.merge(urb_pref, on="_key_norm", how="left").drop(columns="_key_norm")

            # cobertura final
            cov_urb = base.filter(like="URB__").notna().any(axis=1).sum()
            print(f"[MERGE URBAN • refeito após PATCH] cobertura={cov_urb}/{len(base)}")

            # confirmar linha corrigida
            print(
                base.loc[base["nome_mun"].str.contains("Gracho Cardoso", case=False, na=False),
                         ["cod_mun","uf","nome_mun","URB__Total","URB__Urbana","URB__Rural"]]
                .to_string(index=False)
            )
        else:
            print("\n[PATCH URBAN] Aviso: não encontrei 'Graccho Cardoso' no df_urban_fixed para corrigir.")

df_urban_fixed: 5 colunas — (nome_mun, Total, Urbana, Rural, uf)
[MERGE URBAN] cols=61 | cobertura=5569/5570

[CONSISTÊNCIA URBAN]
 - Linhas: 5570 (esperado: 5570)
 - Colunas antes: 58 | depois: 61 | adicionadas: 3

[URBAN] Faltantes: 1
 cod_mun uf       nome_mun
 2802601 SE Gracho Cardoso

[PATCH URBAN] Corrigido nome em df_urban_fixed: 'Graccho Cardoso' → 'Gracho Cardoso' (SE). Linhas alteradas: 1
[MERGE URBAN • refeito após PATCH] cobertura=5570/5570
 cod_mun uf       nome_mun  URB__Total  URB__Urbana URB__Rural
 2802601 SE Gracho Cardoso        5834         2905       2929

In [29]:
# ======================================================
# VALIDAÇÃO — Integração BASE × URBAN
# ======================================================

print("\n[VALIDAÇÃO URBAN]")

# 1️⃣ Contagens gerais
print(f"Total de linhas em BASE: {len(base)}")
print(f"Total de linhas em URBAN: {len(df_urban_fixed)}")

# Guardar contagem de colunas anterior e posterior
cols_antes = len([c for c in base.columns if not c.startswith("URB__")])
cols_depois = len(base.columns)
cols_adicionadas = len([c for c in base.columns if c.startswith("URB__")])

print(f"\n[COLUNAS]")
print(f" - Colunas antes: {cols_antes}")
print(f" - Colunas depois: {cols_depois}")
print(f" - Colunas adicionadas (URB__): {cols_adicionadas}")

# 2️⃣ Cobertura do merge
cov_urb = base.filter(like="URB__").notna().any(axis=1).sum()
perc_cov = cov_urb / len(base) * 100
print(f"\n[Cobertura URBAN] {cov_urb}/{len(base)} ({perc_cov:.2f}%)")

# 3️⃣ Municípios faltantes
faltantes = base.loc[~base.filter(like="URB__").notna().any(axis=1),
                     ["cod_mun", "uf", "nome_mun"]]
print(f"\n[FALTANTES] Municípios sem correspondência no URBAN: {len(faltantes)}")
if not faltantes.empty:
    print(faltantes.head(10).to_string(index=False))

# 4️⃣ Amostra de correspondências corretas
print("\n[Amostra de correspondências BASE × URBAN]")
cols_check = ["cod_mun", "uf", "nome_mun"] + [c for c in base.columns if c.startswith("URB__")][:3]
print(base[cols_check].dropna().sample(5, random_state=42).to_string(index=False))

# 5️⃣ Verificação de chaves divergentes (diagnóstico de nomes)
base_keys = set(base["uf"] + "_" + base["nome_mun"].apply(nome_norm_strong))
urb_keys = set(df_urban_fixed["uf"] + "_" + df_urban_fixed["nome_mun"].apply(nome_norm_strong))
diff = base_keys - urb_keys
print(f"\n[CHAVES NÃO BATENDO] {len(diff)} possíveis divergências textuais")
if len(diff) > 0:
    print(list(diff)[:10])

[VALIDAÇÃO URBAN]
Total de linhas em BASE: 5570
Total de linhas em URBAN: 5570

[COLUNAS]
 - Colunas antes: 58
 - Colunas depois: 61
 - Colunas adicionadas (URB__): 3

[Cobertura URBAN] 5570/5570 (100.00%)

[FALTANTES] Municípios sem correspondência no URBAN: 0

[Amostra de correspondências BASE × URBAN]
 cod_mun uf   nome_mun  URB__Total  URB__Urbana URB__Rural
 2408607 RN     Paraná        3934         2399       1535
 2205102 PI   Itaueira       10323         6370       3953
 2100907 MA   Araioses       39052        11187      27865
 2403806 RN   Florânia       10196         7250       2946
 5101258 MT Araputanga       14786        12541       2245

[CHAVES NÃO BATENDO] 0 possíveis divergências textuais

## 5.6 - Checking Point dos Merges

In [30]:
# ======================================================
# CHECKPOINT — Evolução dos merges (PIB → POP → LAT → URB)
# Objetivo:
#   • Resumir a evolução da BASE após as integrações feitas até agora.
#   • Mostrar: nº de linhas, nº de colunas por bloco, colunas adicionadas,
#     cobertura por dataset (linhas com pelo menos 1 valor no bloco).
# Pré-requisitos:
#   • 'base' já contém: colunas originais do PIB (sem prefixo) + POP__* + LAT__* + URB__*
#   • Função resumo_colunas (opcional) e merges anteriores executados.
# ======================================================

import pandas as pd

# 1) Definir prefixos dos blocos já integrados
PREFIXOS = {
    "POP": "POP__",
    "LAT": "LAT__",
    "URB": "URB__",
    # "IDHM": "IDHM__"  # (ainda não integrado neste checkpoint)
}

# 2) Inferir colunas do núcleo PIB (sem prefixo)
def colunas_pib_nucleo(df: pd.DataFrame) -> list:
    pref_list = list(PREFIXOS.values())
    return [c for c in df.columns if not any(c.startswith(p) for p in pref_list)]

cols_pib_core = colunas_pib_nucleo(base)

# 3) Funções auxiliares para contagem/cobertura por bloco
def cols_do_bloco(df: pd.DataFrame, prefixo: str) -> list:
    return [c for c in df.columns if c.startswith(prefixo)]

def cobertura_bloco(df: pd.DataFrame, prefixo: str) -> int:
    cols = cols_do_bloco(df, prefixo)
    return df[cols].notna().any(axis=1).sum() if cols else 0

# 4) Montar tabela-resumo
linhas = []
total_linhas = len(base)

# Linha do núcleo PIB (sem prefixos)
linhas.append({
    "Bloco": "PIB (núcleo)",
    "Linhas": total_linhas,
    "Colunas do bloco": len(cols_pib_core),
    "Cobertura (linhas com dados)": total_linhas,   # núcleo está presente em 100%
    "Cobertura (%)": 100.0,
    "Exemplo de colunas": ", ".join(cols_pib_core[:5]) + ("..." if len(cols_pib_core) > 5 else "")
})

# Linhas por cada bloco integrado
for nome, pref in PREFIXOS.items():
    cols_blk = cols_do_bloco(base, pref)
    cov     = cobertura_bloco(base, pref)
    linhas.append({
        "Bloco": nome,
        "Linhas": total_linhas,
        "Colunas do bloco": len(cols_blk),
        "Cobertura (linhas com dados)": cov,
        "Cobertura (%)": round((cov / total_linhas) * 100, 2) if total_linhas else 0.0,
        "Exemplo de colunas": ", ".join(cols_blk[:5]) + ("..." if len(cols_blk) > 5 else "")
    })

resumo = pd.DataFrame(linhas)

# 5) Adicionar coluna de "Colunas acumuladas" para visualizar evolução
#    (PIB + POP + LAT + URB, na ordem apresentada na tabela)
resumo["Colunas acumuladas"] = resumo["Colunas do bloco"].cumsum()

In [31]:
from textwrap import shorten

# Copiar para não mexer no original
resumo_fmt = resumo.copy()

# Quebrar/encurtar o texto de exemplos para não estourar a largura
resumo_fmt["Exemplo de colunas"] = resumo_fmt["Exemplo de colunas"].apply(
    lambda s: shorten(s, width=120, placeholder="...")
)

# Renomear colunas para cabeçalhos mais curtos
resumo_fmt = resumo_fmt.rename(columns={
    "Bloco": "Bloco",
    "Linhas": "Linhas",
    "Colunas do bloco": "Cols do bloco",
    "Cobertura (linhas com dados)": "Cobertura (linhas)",
    "Cobertura (%)": "Cobertura (%)",
    "Exemplo de colunas": "Exemplos",
    "Colunas acumuladas": "Cols acumuladas"
})

# Formatação numérica
format_dict = {
    "Linhas": "{:,.0f}".format,
    "Cols do bloco": "{:,.0f}".format,
    "Cobertura (linhas)": "{:,.0f}".format,
    "Cobertura (%)": "{:.2f}".format,
    "Cols acumuladas": "{:,.0f}".format
}

# Estilo com linhas, zebra e largura controlada
styled = (
    resumo_fmt.style
    .set_table_styles(
        [
            {"selector": "table", "props": [("border-collapse", "collapse"), ("width", "100%")]},
            {"selector": "th, td", "props": [("border", "1px solid #bbb"), ("padding", "6px 8px"), ("vertical-align","top")]},
            {"selector": "thead th", "props": [("background-color", "#f2f2f2"), ("font-weight", "600")]}
        ],
        overwrite=True
    )
    .set_properties(**{"text-align": "left"})
    .hide(axis="index")
    .format(format_dict, na_rep="—")
    .apply(
        lambda s: ["background-color: #fcfcfc" if i % 2 else "" for i in range(len(s))],
        axis=0
    )
)

# Cabeçalho com shape atual
print(f"📌 CHECKPOINT — Evolução dos merges (PIB → POP → LAT → URB)\n")
print(f"Shape atual da BASE: {base.shape[0]:,} linhas × {base.shape[1]:,} colunas\n")

display(styled)

📌 CHECKPOINT — Evolução dos merges (PIB → POP → LAT → URB)

Shape atual da BASE: 5,570 linhas × 61 colunas

## 5.7 - Integrando df idhm_expanded

In [32]:
# ======================================================
# BLOCO 5 — Merge IDHM (df_idhm_final)
# Objetivo:
#   • Integrar df_idhm_final à BASE.
#   • Preferir merge por 'cod_mun'; fallback por (uf + nome_mun) normalizado.
#   • Evitar _x/_y limpando IDHM__* antes do merge e deduplicando a chave.
# Pré-requisitos:
#   • base já contém PIB + POP + LAT + URB
#   • df_idhm_final disponível (colunas podem variar: cod_mun/uf/nome_mun)
#   • função nome_norm_strong disponível (Bloco 0)
# ======================================================

# 0) Limpeza preventiva: remover colunas IDHM__ antigas
base = base.drop(columns=[c for c in base.columns if c.startswith("IDHM__")], errors="ignore")

# 1) Resumo e sanidade mínima
resumo_colunas(df_idhm_final, "df_idhm_final", max_cols=8)
assert "nome_mun" in df_idhm_final.columns, "df_idhm_final precisa ter 'nome_mun'."

cols_antes = len(base.columns)

# ==========================
# Caminho A — por cod_mun
# ==========================
if "cod_mun" in df_idhm_final.columns:
    idhm_add = df_idhm_final.copy()

    # Harmonizar tipo da chave
    base["cod_mun"]     = pd.to_numeric(base["cod_mun"], errors="coerce").astype("Int64")
    idhm_add["cod_mun"] = pd.to_numeric(idhm_add["cod_mun"], errors="coerce").astype("Int64")

    # Deduplicar por cod_mun
    idhm_add = idhm_add.drop_duplicates(subset=["cod_mun"]).copy()

    # Prefixar métricas/atributos (tudo exceto cod_mun)
    cols_metrics_idhm = [c for c in idhm_add.columns if c != "cod_mun"]
    idhm_pref = pd.concat(
        [idhm_add[["cod_mun"]], idhm_add[cols_metrics_idhm].add_prefix("IDHM__")],
        axis=1
    )

    # Merge 1:1 por cod_mun
    base = base.merge(idhm_pref, on="cod_mun", how="left", validate="1:1")
    caminho = "cod_mun"

# =======================================
# Caminho B — por (uf + nome) normalizado
# =======================================
else:
    idhm_add = df_idhm_final.copy()

    # Se não houver 'uf', tentar extrair do sufixo "(UF)" em nome_mun
    if "uf" not in idhm_add.columns or idhm_add["uf"].isna().all():
        idhm_add["uf"] = idhm_add["nome_mun"].str.extract(r"\((\w{2})\)\s*$")[0]
        idhm_add["nome_mun"] = idhm_add["nome_mun"].str.replace(r"\s*\(\w{2}\)\s*$", "", regex=True).str.strip()

    assert "uf" in idhm_add.columns, "Não foi possível obter a coluna 'uf' no df_idhm_final."

    # Criar chaves normalizadas nos dois lados
    b = base.copy()
    b["_key_norm"]      = b["uf"].astype(str) + "_" + b["nome_mun"].apply(nome_norm_strong)
    idhm_add["_key_norm"] = idhm_add["uf"].astype(str) + "_" + idhm_add["nome_mun"].apply(nome_norm_strong)

    # Deduplicar por chave
    idhm_add = idhm_add.drop_duplicates(subset=["_key_norm"]).copy()

    # Prefixar métricas
    cols_metrics_idhm = [c for c in idhm_add.columns if c not in ["_key_norm","uf","nome_mun"]]
    idhm_pref = pd.concat([idhm_add[["_key_norm"]], idhm_add[cols_metrics_idhm].add_prefix("IDHM__")], axis=1)

    # Merge
    base = b.merge(idhm_pref, on="_key_norm", how="left").drop(columns="_key_norm")
    caminho = "(uf+nome_norm)"

# ============== Relatórios
cov_idhm = base.filter(like="IDHM__").notna().any(axis=1).sum()
print(f"[MERGE IDHM] via {caminho} | cols={len(base.columns)} | cobertura={cov_idhm}/{len(base)}")

print("\n[CONSISTÊNCIA IDHM]")
print(f" - Linhas: {len(base)} (esperado: 5570)")
print(f" - Colunas antes: {cols_antes} | depois: {len(base.columns)} | adicionadas: {len(base.columns) - cols_antes}")

# Faltantes (sem nenhum valor IDHM__)
faltantes_mask = ~base.filter(like="IDHM__").notna().any(axis=1)
faltantes = base.loc[faltantes_mask, ["cod_mun","uf","nome_mun"]].copy()
print(f"\n[IDHM] Faltantes: {len(faltantes)}")
if len(faltantes) > 0:
    print(faltantes.head(20).to_string(index=False))

df_idhm_final: 17 colunas — (nome_mun, IDHM 2010, Produto Interno Bruto per capita 2013, Produto Interno Bruto per capita 2014, Produto Interno Bruto per capita 2015, Produto Interno Bruto per capita 2016, População total 2012, População total 2013... (+9))
[MERGE IDHM] via (uf+nome_norm) | cols=76 | cobertura=5554/5570

[CONSISTÊNCIA IDHM]
 - Linhas: 5570 (esperado: 5570)
 - Colunas antes: 61 | depois: 76 | adicionadas: 15

[IDHM] Faltantes: 16
 cod_mun uf               nome_mun
 1506500 PA   Santa Izabel do Pará
 1708254 TO                Tabocão
 2306306 CE                Itapajé
 2401305 RN           Campo Grande
 2410306 RN           Serra Caiada
 2513653 PB          Joca Claudino
 2515401 PB  São Vicente do Seridó
 2606903 PE               Iguaracy
 2928505 BA        Santa Terezinha
 3108909 MG             Brazópolis
 3122900 MG           Dona Euzébia
 3165206 MG    São Tomé das Letras
 3515004 SP         Embu das Artes
 3516101 SP               Florínea
 3550001 SP São Luiz do Paraitinga
 5107008 MT                Poxoréu

### 5.7.1 - Correção de inconsistências

In [38]:
# ===========================================
# PATCH DE NOMES (IDHM -> BASE) + RE-MERGE (CORRIGIDO)
# ===========================================
import pandas as pd
import unicodedata, re

# fallback da normalização
if "nome_norm_strong" not in globals():
    def nome_norm_strong(s: str) -> str:
        STOP = {"de","da","do","das","dos"}
        if pd.isna(s): return ""
        s = str(s).lower().strip()
        s = unicodedata.normalize("NFKD", s).encode("ascii","ignore").decode("utf-8")
        s = s.replace("’","'").replace("´","'").replace("`","'")
        s = s.replace("-", " ").replace("/", " ")
        s = re.sub(r"[^a-z0-9 ']+", " ", s)
        s = " ".join(s.split())
        tokens = [t for t in s.split() if t not in STOP]
        return "_".join(tokens)

# 🔧 Corrija o dicionário: NUNCA troque Tupirama->Tabocão
PATCHES_IDHM_TO_BASE = {
    # históricos/ortografia
    ("PA","Santa Isabel do Pará"): "Santa Izabel do Pará",
    # ("TO","Tupirama"): "Tabocão",  # ❌ REMOVIDO (estava invertido)
    ("TO","Tabocão"): "Fortaleza do Tabocao",    # ✅ CORRETO
    ("CE","Itapaje"): "Itapajé",
    ("RN","Augusto Severo"): "Campo Grande",
    ("RN","Presidente Juscelino"): "Serra Caiada",
    ("PB","Santarém"): "Joca Claudino",
    ("PB","Seridó"): "São Vicente do Seridó",
    ("PE","Iguaraci"): "Iguaracy",
    ("BA","Santa Teresinha"): "Santa Terezinha",
    ("MG","Brazopolis"): "Brazópolis",
    ("MG","Dona Eusebia"): "Dona Euzébia",
    ("MG","São Thomé das Letras"): "São Tomé das Letras",
    ("SP","Embu"): "Embu das Artes",
    ("SP","Florinea"): "Florínea",
    ("SP","São Luís do Paraitinga"): "São Luiz do Paraitinga",
    ("MT","Poxoreo"): "Poxoréu",
    # ajustes finos
    ("CE","Itapagé"): "Itapajé",
    ("MG","Brasópolis"): "Brazópolis",
    ("MG","Dona Eusébia"): "Dona Euzébia",
    ("SP","Florínia"): "Florínea",
    ("MT","Poxoréo"): "Poxoréu",
}

def aplicar_patches(df, patches):
    df = df.copy()
    df["nome_mun"] = df["nome_mun"].astype(str).str.strip()
    mask = df.apply(lambda r: (r["uf"], r["nome_mun"]) in patches, axis=1)
    if mask.any():
        df.loc[mask, "nome_mun"] = df.loc[mask].apply(lambda r: patches[(r["uf"], r["nome_mun"])], axis=1)
    return df

def merge_idhm_enxuto(base, df_idhm):
    base = base.drop(columns=[c for c in base.columns if c.startswith("IDHM__")], errors="ignore")
    b = base.copy()
    b["_key_norm"] = b["uf"].astype(str).str.upper().str.strip() + "_" + b["nome_mun"].apply(nome_norm_strong)

    idhm = df_idhm.copy()
    idhm["uf"] = idhm["uf"].astype(str).str.upper().str.strip()
    idhm["nome_mun"] = idhm["nome_mun"].astype(str).str.strip()
    idhm["_key_norm"] = idhm["uf"] + "_" + idhm["nome_mun"].apply(nome_norm_strong)
    idhm = idhm.drop_duplicates(subset=["_key_norm"])

    cols_metrics = [c for c in idhm.columns if c not in ["_key_norm","uf","nome_mun","cod_mun"]]
    idhm_pref = pd.concat([idhm[["_key_norm"]], idhm[cols_metrics].add_prefix("IDHM__")], axis=1)

    cols_antes = len(base.columns)
    merged = b.merge(idhm_pref, on="_key_norm", how="left").drop(columns="_key_norm")

    cov = merged.filter(like="IDHM__").notna().any(axis=1).sum()
    print(f"[MERGE IDHM] cols={len(merged.columns)} | cobertura={cov}/{len(merged)} | +{len(merged.columns)-cols_antes} colunas")

    falt = merged.loc[~merged.filter(like="IDHM__").notna().any(axis=1), ["cod_mun","uf","nome_mun"]]
    print(f"[IDHM] Faltantes: {len(falt)}")
    if not falt.empty:
        print(falt.head(10).to_string(index=False))
    return merged

# 👉 Aplicar patch e re-merge
df_idhm_patched = aplicar_patches(df_idhm_final, PATCHES_IDHM_TO_BASE)
base = merge_idhm_enxuto(base, df_idhm_patched)

# (Opcional) assert para garantir que Tupirama (TO) casou
ok_tupi = (base["uf"].eq("TO") & base["nome_mun"].eq("Tupirama") & base.filter(like="IDHM__").notna().any(axis=1)).any()
print("✅ Tupirama(TO) casou com IDHM?" , bool(ok_tupi))

[MERGE IDHM] cols=76 | cobertura=5570/5570 | +15 colunas
[IDHM] Faltantes: 0
✅ Tupirama(TO) casou com IDHM? True

In [39]:
# corrigir automaticamente o nome no base e/ou IDHM
# 	“Tabocão” e “Fortaleza do Tabocão” referem-se ao mesmo município (código IBGE 1708254).

base.loc[base["cod_mun"] == 1708254, "nome_mun"] = "Fortaleza do Tabocão"

## 5.8 - Checking Point Final

In [40]:
# ======================================================
# CHECKPOINT — Evolução dos merges (CORE → LAT → POP → PIB → URB → IDHM)
# CORE = apenas chaves mínimas; LAT detecta pref/puro; PIB = restante sem prefixo
# ======================================================
import pandas as pd
from textwrap import shorten

# 1) Definições
CORE_KEYS = ["cod_mun", "uf", "nome_mun"]
LAT_RAW   = {"lat","lon","capital","ddd","siafi_id","fuso_horario"}  # possíveis cols LAT sem prefixo
PREFIXOS  = {"POP":"POP__", "URB":"URB__", "IDHM":"IDHM__", "PIB":"PIB__", "LAT":"LAT__"}  # prefixos já padronizados

def has_col(df, c): return c in df.columns
def cols_start(df, p): return [c for c in df.columns if c.startswith(p)]

# 2) Núcleo CORE (apenas chaves)
core_cols = [c for c in CORE_KEYS if c in base.columns]
# 2.1) LAT — pode vir com prefixo (LAT__) ou cru (lat, lon, …)
lat_cols_pref = cols_start(base, PREFIXOS["LAT"])
lat_cols_raw  = [c for c in LAT_RAW if c in base.columns]
lat_cols = sorted(set(lat_cols_pref + lat_cols_raw))

# 3) Colunas sem prefixo (candidatas a serem do PIB puro)
pref_list = [p for k,p in PREFIXOS.items()]
non_pref = [c for c in base.columns if not any(c.startswith(p) for p in pref_list)]
# 3.1) Remover CORE e LAT cru do conjunto não-prefixado → o que sobrar é PIB puro
pib_puro = [c for c in non_pref if c not in set(core_cols) | set(lat_cols_raw)]

# 4) Blocos com prefixo
pop_cols  = cols_start(base, PREFIXOS["POP"])
urb_cols  = cols_start(base, PREFIXOS["URB"])
idhm_cols = cols_start(base, PREFIXOS["IDHM"])
# (PIB pode ser misto: sem prefixo = pib_puro; com prefixo = PIB__*)
pib_pref  = cols_start(base, PREFIXOS["PIB"])

# 5) Função cobertura
def cobertura(cols):
    if not cols: return 0
    return base[cols].notna().any(axis=1).sum()

# 6) Monta a tabela na ordem desejada
linhas = []
total = len(base)

def add_row(nome, cols):
    if not cols: 
        return
    linhas.append({
        "Bloco": nome,
        "Linhas": total,
        "Cols do bloco": len(cols),
        "Cobertura (linhas)": cobertura(cols),
        "Cobertura (%)": round(cobertura(cols)/total*100, 2) if total else 0.0,
        "Exemplos": ", ".join(cols[:5]) + ("..." if len(cols) > 5 else "")
    })

# CORE (chaves)
add_row("CORE (chaves mínimas)", core_cols)

# LAT (pref +/ou cru)
add_row("LAT", lat_cols)

# POP
add_row("POP", pop_cols)

# PIB (puro sem prefixo + com prefixo, se existir)
pib_cols_total = pib_puro + pib_pref
add_row("PIB", pib_cols_total)

# URB
add_row("URB", urb_cols)

# IDHM
add_row("IDHM", idhm_cols)

resumo = pd.DataFrame(linhas)
resumo["Cols acumuladas"] = resumo["Cols do bloco"].cumsum()

# 7) Estilo
resumo_fmt = resumo.copy()
resumo_fmt["Exemplos"] = resumo_fmt["Exemplos"].apply(lambda s: shorten(s, width=120, placeholder="..."))

fmt = {
    "Linhas": "{:,.0f}".format,
    "Cols do bloco": "{:,.0f}".format,
    "Cobertura (linhas)": "{:,.0f}".format,
    "Cobertura (%)": "{:.2f}".format,
    "Cols acumuladas": "{:,.0f}".format,
}

styled = (
    resumo_fmt.style
    .set_table_styles(
        [
            {"selector":"table","props":[("border-collapse","collapse"),("width","100%")]},
            {"selector":"th, td","props":[("border","1px solid #bbb"),("padding","6px 8px"),("vertical-align","top")]},
            {"selector":"thead th","props":[("background-color","#f2f2f2"),("font-weight","600")]}
        ],
        overwrite=True
    )
    .set_properties(**{"text-align":"left"})
    .hide(axis="index")
    .format(fmt, na_rep="—")
    .apply(lambda s: ["background-color: #fcfcfc" if i % 2 else "" for i in range(len(s))], axis=0)
)

print("📌 CHECKPOINT — Evolução dos merges (CORE → LAT → POP → PIB → URB → IDHM)\n")
print(f"Shape atual da BASE: {base.shape[0]:,} linhas × {base.shape[1]:,} colunas\n")
display(styled)

# (Opcional) faltantes por bloco
for nome, cols in [
    ("LAT", lat_cols),
    ("POP", pop_cols),
    ("PIB", pib_cols_total),
    ("URB", urb_cols),
    ("IDHM", idhm_cols),
]:
    if not cols: 
        continue
    falt = base.loc[~base[cols].notna().any(axis=1), ["cod_mun","uf","nome_mun"]]
    print(f"\n[{nome}] Faltantes: {len(falt)}")
    if not falt.empty:
        print(falt.head(10).to_string(index=False))

📌 CHECKPOINT — Evolução dos merges (CORE → LAT → POP → PIB → URB → IDHM)

Shape atual da BASE: 5,570 linhas × 76 colunas

[LAT] Faltantes: 0

[POP] Faltantes: 0

[PIB] Faltantes: 0

[URB] Faltantes: 0

[IDHM] Faltantes: 0

## 6. Exportação - Arquivo Dados Socio Economicos Consolidados

In [41]:
base.to_excel("base_socioeconomica_completa.xlsx", index=False, engine="openpyxl")